import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'app.dart';
import 'core/constants/app_colors.dart';
import 'firebase_options.dart';

/// Compile-time backend switch: `flutter run --dart-define=USE_EMULATOR=true`
/// points the app at the local Firebase emulator suite (same define the
/// integration tests use). Default is OFF → production.
const bool _emulatorDefine = bool.fromEnvironment('USE_EMULATOR');

/// Belt and braces: also require debug mode. Both operands are compile-time
/// consts, so in release/profile builds this is `false` at compile time and
/// the localhost hookup below is dead code — a release build is structurally
/// incapable of targeting the emulators even if the define is passed.
const bool _useEmulators = kDebugMode && _emulatorDefine;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase (options generated by `flutterfire configure`)
  final firebaseApp = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // App Check attests that a request came from a genuine build of this app.
  // It has to run before the first Auth/Firestore/Storage touch so those calls
  // carry a token — the same window the backend hookup below relies on.
  //
  // NOT enforced server-side. Until enforcement is turned on in the console
  // this is observe-only: unattested requests are still served, so a failure
  // here degrades attestation, it does not lock anyone out.
  await FirebaseAppCheck.instance.activate(
    // App Attest needs real hardware and a provisioned team, which a simulator
    // cannot provide. Debug builds therefore use the debug provider, which
    // prints a token to the log to be registered in the Firebase console.
    appleProvider: kDebugMode ? AppleProvider.debug : AppleProvider.appAttest,
  );

  // Backend hookup MUST sit between initializeApp and the first Auth/
  // Firestore/Storage touch. Nothing reaches Firebase before runApp (no
  // eager top-level singletons; services hit FirebaseFirestore.instance
  // lazily inside methods), so this spot is safe by construction.
  if (_useEmulators) {
    // Host/ports mirror firebase.json. 127.0.0.1, NOT localhost — the
    // emulators bind IPv4 explicitly and localhost can resolve to ::1 on iOS.
    await FirebaseAuth.instance.useAuthEmulator('127.0.0.1', 9099);
    FirebaseFirestore.instance.useFirestoreEmulator('127.0.0.1', 8080);
    await FirebaseStorage.instance.useStorageEmulator('127.0.0.1', 9199);
    debugPrint('>>> BACKEND: EMULATOR (127.0.0.1 — auth:9099 firestore:8080 storage:9199)');
    debugPrint('>>> An emulator-minted auth session is INVALID against production: '
        'uninstall the app before switching backends.');
  } else {
    debugPrint('>>> BACKEND: PRODUCTION (${firebaseApp.options.projectId})');
  }

  // Local storage
  await Hive.initFlutter();

  // Relative-time messages
  timeago.setLocaleMessages('en', timeago.EnMessages());
  timeago.setLocaleMessages('en_short', timeago.EnShortMessages());

  // Premium dark chrome, portrait-locked
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: AppColors.background,
    systemNavigationBarIconBrightness: Brightness.light,
  ));
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  runApp(const ProviderScope(child: AniSphereApp()));
}
