/// One entry in the offline Emoji Anime bank: an emoji riddle and the anime
/// title it represents.
class EmojiAnimeEntry {
  final String emojis;
  final String title;
  const EmojiAnimeEntry(this.emojis, this.title);
}

/// Offline bank of emoji → anime riddles covering globally popular titles.
/// Each riddle should be guessable on its own and unambiguous within the bank
/// (no two entries share a title, and no riddle fits another entry better).
const List<EmojiAnimeEntry> emojiAnimeBank = [
  EmojiAnimeEntry('🏴‍☠️👒🍖', 'One Piece'),
  EmojiAnimeEntry('🍥🦊🥷', 'Naruto'),
  EmojiAnimeEntry('🧱⚔️🦅', 'Attack on Titan'),
  EmojiAnimeEntry('📓🍎💀', 'Death Note'),
  EmojiAnimeEntry('🗡️👹🌊', 'Demon Slayer'),
  EmojiAnimeEntry('💥🦸🏫', 'My Hero Academia'),
  EmojiAnimeEntry('⚗️🦾⭕', 'Fullmetal Alchemist: Brotherhood'),
  EmojiAnimeEntry('👨‍🦲👊💯', 'One Punch Man'),
  EmojiAnimeEntry('🐉✨🥋', 'Dragon Ball Z'),
  EmojiAnimeEntry('👁️🤞👹', 'Jujutsu Kaisen'),
  EmojiAnimeEntry('🕵️🥜🔫', 'Spy x Family'),
  EmojiAnimeEntry('🎣⚡🃏', 'Hunter x Hunter'),
  EmojiAnimeEntry('🎭☕🩸', 'Tokyo Ghoul'),
  EmojiAnimeEntry('🪚😈🐶', 'Chainsaw Man'),
  EmojiAnimeEntry('🎮⚔️💘', 'Sword Art Online'),
  EmojiAnimeEntry('🏐🐥🔥', 'Haikyuu!!'),
  EmojiAnimeEntry('🏀👻🌈', "Kuroko's Basketball"),
  EmojiAnimeEntry('⚽🔒🥅', 'Blue Lock'),
  EmojiAnimeEntry('⚡🐭🔴', 'Pokémon'),
  EmojiAnimeEntry('⚔️👻🍊', 'Bleach'),
  EmojiAnimeEntry('🧚🔥🐉', 'Fairy Tail'),
  EmojiAnimeEntry('🍀📖⚔️', 'Black Clover'),
  EmojiAnimeEntry('7️⃣🐗🍺', 'The Seven Deadly Sins'),
  EmojiAnimeEntry('🧪🗿🌿', 'Dr. Stone'),
  EmojiAnimeEntry('🧒🏚️👹', 'The Promised Neverland'),
  EmojiAnimeEntry('🔮💯🥋', 'Mob Psycho 100'),
  EmojiAnimeEntry('♟️👁️🤖', 'Code Geass'),
  EmojiAnimeEntry('🤖👼🌍', 'Neon Genesis Evangelion'),
  EmojiAnimeEntry('🤠🚀🎷', 'Cowboy Bebop'),
  EmojiAnimeEntry('⏳🔬📱', 'Steins;Gate'),
  EmojiAnimeEntry('🎲👑🎮', 'No Game No Life'),
  EmojiAnimeEntry('🔁💀👧', 'Re:Zero'),
  EmojiAnimeEntry('🧙‍♀️💥🐸', 'Konosuba'),
  EmojiAnimeEntry('💀👑🏰', 'Overlord'),
  EmojiAnimeEntry('💧🔵👑', 'That Time I Got Reincarnated as a Slime'),
  EmojiAnimeEntry('⏰🏍️👊', 'Tokyo Revengers'),
  EmojiAnimeEntry('🪓🛶❄️', 'Vinland Saga'),
  EmojiAnimeEntry('🗡️🩸🌑', 'Berserk'),
  EmojiAnimeEntry('🧛⭐💪', "JoJo's Bizarre Adventure"),
  EmojiAnimeEntry('🔥👨‍🚒😈', 'Fire Force'),
  EmojiAnimeEntry('🤵😈🫖', 'Black Butler'),
  EmojiAnimeEntry('🧺🐱🐭', 'Fruits Basket'),
  EmojiAnimeEntry('🎹🎻🌸', 'Your Lie in April'),
  EmojiAnimeEntry('🤟💌😢', 'A Silent Voice'),
  EmojiAnimeEntry('☄️👫🔴', 'Your Name'),
  EmojiAnimeEntry('🏮🐉🛁', 'Spirited Away'),
  EmojiAnimeEntry('🐺👸🌲', 'Princess Mononoke'),
  EmojiAnimeEntry('🌳☔🐾', 'My Neighbor Totoro'),
  EmojiAnimeEntry('🏰🔥💍', "Howl's Moving Castle"),
  EmojiAnimeEntry('💌🦾👰', 'Violet Evergarden'),
  EmojiAnimeEntry('🕳️🎒🤖', 'Made in Abyss'),
  EmojiAnimeEntry('🛡️🦝⚔️', 'The Rising of the Shield Hero'),
  EmojiAnimeEntry('⏪🧒❄️', 'Erased'),
  EmojiAnimeEntry('🐙🏫🔫', 'Assassination Classroom'),
  EmojiAnimeEntry('👨‍🍳🔥🏆', 'Food Wars'),
  EmojiAnimeEntry('👑❤️🧠', 'Kaguya-sama: Love Is War'),
  EmojiAnimeEntry('🐯🐉❤️', 'Toradora!'),
  EmojiAnimeEntry('🍡🌸😭', 'Clannad'),
  EmojiAnimeEntry('👼🎸🔫', 'Angel Beats!'),
  EmojiAnimeEntry('5️⃣👯💍', 'The Quintessential Quintuplets'),
  EmojiAnimeEntry('🗡️🆙🕶️', 'Solo Leveling'),
  EmojiAnimeEntry('🧝⏳🪄', 'Frieren: Beyond Journey\'s End'),
  EmojiAnimeEntry('⭐👶🎤', 'Oshi no Ko'),
  EmojiAnimeEntry('🎸😰🎀', 'Bocchi the Rock!'),
];
