/// All user-facing UI strings. Never hardcode copy in widgets — pull from here
/// via `LanguageProvider.t(key)` so the whole app is translatable + RTL-ready.
class AppStrings {
  AppStrings._();

  static const List<LangMeta> languages = [
    LangMeta('ar', 'العربية', '🇸🇦', isRTL: true),
    LangMeta('en', 'English', '🇺🇸'),
    LangMeta('ja', '日本語', '🇯🇵'),
    LangMeta('ko', '한국어', '🇰🇷'),
    LangMeta('es', 'Español', '🇪🇸'),
    LangMeta('fr', 'Français', '🇫🇷'),
    LangMeta('tr', 'Türkçe', '🇹🇷'),
    LangMeta('id', 'Indonesia', '🇮🇩'),
  ];

  static const Map<String, Map<String, String>> values = {
    'en': {
      'vote': 'Vote',
      'communityVoteTitle': 'Today\'s Community Vote',
      'castVote': 'Cast a Vote',
      'votesRemaining': 'Votes remaining',
      'resetsIn': 'Resets in',
      'cantBeUndone': 'This can\'t be undone.',
      'voteForConfirm': 'Vote for',
      'alreadyVotedToday': 'You already voted for this anime today',
      'noVotesLeftToday': 'No votes left today',
      'yourVotesToday': 'Your Votes Today',
      'todaysLeaderboard': 'Today\'s Leaderboard',
      'viewPastDays': 'View Past Days',
      'pastVotesTitle': 'Past Community Votes',
      'upgradeForVotes': 'AniPlus: 4 votes/day',
      'voteCastSuccess': 'Vote cast! 🎉',
      'noVotesYetToday': 'No votes yet today — be the first!',
      'searchAnimeHint': 'Search anime…',
      'recentSearches': 'Recent searches',
      'noAnimeFound': 'No anime found for',
      'tagline': 'Your World. Your Anime.',
      'feed': 'Feed',
      'discover': 'Discover',
      'create': 'Create',
      'rooms': 'Rooms',
      'community': 'Community',
      'profile': 'Profile',
      'aniVideos': 'Ani Videos',
      'challenges': 'Challenges',
      'seasonal': 'Seasonal',
      'achievements': 'Achievements',
      'wallet': 'Wallet',
      'observatory': 'Observatory',
      'fmRadio': 'FM Radio',
      'cardCollection': 'Card Collection',
      'settings': 'Settings',
      'myList': 'My List',
      'save': 'Save',
      'cancel': 'Cancel',
      'displayName': 'Display Name',
      'bio': 'Bio',
      'usernameChecking': 'Checking…',
      'usernameAvailable': 'Available ✓',
      'usernameTaken': 'Already taken',
      'usernameTooShort': 'At least 3 characters',
      'usernameInvalid': 'Lowercase letters, numbers and _ only',
      'usernameReserved': 'This name is reserved',
      'usernameCheckFailed': 'Couldn\'t check — try again',
      'claimUsernameTitle': 'Claim your username',
      'claimUsernameBody':
          'Pick your unique @handle. Your display name stays separate and can be changed anytime.',
      'claim': 'Claim',
      'claimLater': 'Not now — you can claim later',
      'usernameClaimFailed': 'Couldn\'t claim — check your connection and try again',
      'uploadPhotoSoon': 'Upload photo (coming soon)',
      'profileUpdated': 'Profile updated ✅',
      'retry': 'Retry',
      'notes': 'Notes',
      'status': 'Status',
      'total': 'Total',
      'removeFromList': 'Remove from List',
      'emptyListTitle': 'Nothing here yet',
      'emptyListBody': 'Add anime to get started',
      'episodesWatched': 'Episodes watched',
      'yourScore': 'Your score',
      'lastUpdated': 'Last updated',
      'listError': "Couldn't update your list. Try again.",
      'continueAsGuest': 'Continue as Guest',
      'guestSignedIn': 'Signed in as guest',
      'guestError': "Couldn't sign in. Try again.",
      'messages': 'Messages',
      'notifications': 'Notifications',
      'selectLanguage': 'Select Language',
      'createAccount': 'Create Account',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'skip': 'Skip',
      'next': 'Next',
      'continueLabel': 'Continue',
      'finishSetup': 'Finish Setup',
      'email': 'Email',
      'username': 'Username',
      'password': 'Password',
      'dateOfBirth': 'Date of Birth',
      'account': 'Account',
      'pickAnime': 'Pick Anime',
      'preferences': 'Preferences',
      'firstAnimeEver': 'Your first anime ever?',
      'whatYouEnjoy': 'What do you enjoy?',
      'ageRestriction': 'Age Restriction ⚠️',
      'ageRestrictionBody': 'AniSphere requires users to be 14 or older.',
      'exit': 'Exit',
      'follow': 'Follow',
      'following': 'Following',
      'followers': 'Followers',
      'followBack': 'Follow Back',
      'message': 'Message',
      'editProfile': 'Edit Profile',
      'like': 'Like',
      'comment': 'Comment',
      'share': 'Share',
      'bookmark': 'Bookmark',
      'translate': 'Translate',
      'translated': 'Translated',
      'showOriginal': 'Show Original',
      'spoiler': 'Spoiler — tap to reveal',
      'trendingThisSeason': 'Trending This Season',
      'dailyTasks': 'Daily Tasks',
      'stories': 'Stories',
      'addStory': 'Add Story',
      'forYou': 'For You',
      'trending': 'Trending',
      'news': 'News',
      'aniMatch': 'AniMatch',
      'chart': 'Chart',
      'search': 'Search',
      'searchHint': 'Search anime, users, posts…',
      'animeSoulmate': 'Find Your Anime Soulmate 💫',
      'match': 'Match',
      'worldwide': 'Worldwide',
      'country': 'Country',
      'addToList': 'Add to List',
      'rate': 'Rate',
      'watching': 'Watching',
      'completed': 'Completed',
      'planning': 'Planning',
      'onHold': 'On Hold',
      'dropped': 'Dropped',
      'episodes': 'Episodes',
      'hours': 'Hours',
      'anime': 'Anime',
      'posts': 'Posts',
      'reviews': 'Reviews',
      'lists': 'Lists',
      'fanArt': 'Fan Art',
      'stats': 'Stats',
      'games': 'Games',
      'trueFan': 'True Fan',
      'league': 'League',
      'events': 'Events',
      'play': 'Play',
      'startChallenge': 'Start Challenge →',
      'playAgain': 'Play Again',
      'shareResult': 'Share Result',
      'whoIsThis': 'Who is this character?',
      'correct': '+1 Correct!',
      'worldRank': 'World Rank',
      'countryRank': 'Country Rank',
      'earn': 'Earn',
      'spend': 'Spend',
      'recharge': 'Recharge',
      'aniPlus': 'AniPlus',
      'subscribeNow': 'Subscribe Now',
      'getVerified': 'Get Verified',
      'luckySpin': 'Lucky Spin',
      'spin': 'Spin',
      'apply': 'Apply',
      'all': 'All',
      'follows': 'Follows',
      'activity': 'Activity',
      'streaks': 'Streaks',
      'tasks': 'Tasks',
      'logout': 'Logout',
      'about': 'About',
      'terms': 'Terms',
      'privacy': 'Privacy',
      'language': 'Language',
      'appearance': 'Appearance',
      'notificationSound': 'Notification Sound',
      'send': 'Send',
      'typing': 'typing…',
      'newPost': 'New Post',
      'uploadAniVideo': 'Upload Ani Video',
      'goLive': 'Go Live',
      'sealed': 'Sealed',
      'openPack': 'Open Pack',
      'plusExclusive': 'AniPlus Exclusive 💎',
      'memberSince': 'Member since',
      'streak': 'Streak',
      'verified': 'Verified',
      'online': 'online',
      'post': 'Post',
      'posted': 'Posted!',
      'newPostHint': 'Share your anime thoughts…',
      'addImage': 'Add Image',
      'tagAnime': 'Tag Anime',
      'markAsSpoiler': 'Mark as spoiler',
      'noPostsYet': 'No posts yet. Follow users to see their posts!',
      'comments': 'Comments',
      'noCommentsYet': 'No comments yet — be the first!',
      'addCommentHint': 'Add a comment…',
      'deletePost': 'Delete Post',
      'reportPost': 'Report Post',
      'postDeleted': 'Post deleted',
      'postReported': 'Report received. Thank you!',
      'postFailed': "Couldn't publish your post. Try again.",
      'maxImagesNote': 'You can add up to 3 images.',
      'imageTooLarge': "Couldn't prepare an image for upload. Try a different image.",
      'actionFailed': 'Something went wrong. Try again.',
      'noInternet': 'No internet connection.',
      'loadFeedError': "Couldn't load the feed.",
      'whyReport': 'Why are you reporting this post?',
      'whyReportUser': 'Why are you reporting this user?',
      'whyReportMessage': 'Why are you reporting this message?',
      // ── Direct Messages ──
      'checkConnection': 'Check your connection and try again.',
      'animeFanFallback': 'Anime fan',
      'sayHi': 'Say hi 👋',
      'blockList': 'Block List',
      'unblock': 'Unblock',
      'block': 'Block',
      'dmListError': 'Messages are unavailable right now.',
      'noMessagesYet': 'No messages yet',
      'noMessagesYetCaption': 'Conversations you start will show up here.',
      'blockListError': 'Block list unavailable',
      'noBlockedConversations': 'No blocked conversations',
      'noBlockedConversationsCaption': 'People you block from a chat will appear here.',
      'unblocking': 'Unblocking…',
      'stillSending': "Still sending — it will go out once you're back online.",
      'sendMessageFailed': "Couldn't send that message.",
      'sendPhotoFailed': "Couldn't send that photo.",
      'conversationBlocked': 'Conversation blocked',
      'conversationUnblocked': 'Conversation unblocked',
      'reactionsBlocked': 'Reactions are unavailable while this conversation is blocked.',
      'reportMessage': 'Report message',
      'reportUser': 'Report user',
      'conversationUnavailable': 'This conversation is unavailable.',
      'messageHint': 'Message…',
      'conversationIsBlocked': 'This conversation is blocked',
      'conversationBlockedCaption': "Messages can't be sent or received right now.",
      'whoCanDM': 'Who can DM',
      'everyone': 'Everyone',
      'friends': 'Friends',
      'whyReportVideo': 'Why are you reporting this video?',
      'reportSpam': 'Spam',
      'reportSpoiler': 'Untagged spoiler',
      'reportAbuse': 'Harassment or abuse',
      'reportOther': 'Other',
      'people': 'People',
      'suggestedForYou': 'Suggested For You',
      'noSuggestions': 'No more suggestions',
      'noFollowersYet': 'No followers yet',
      'notFollowingAnyone': 'Not following anyone yet',
      'userNotFound': 'User not found',
      'searchUsers': 'Search users…',
      'likes': 'Likes',
      'popularThisWeek': 'Popular This Week',
      'emptyFeedFollow': 'Follow users to see posts in your Feed!',
      'startFollowingHint': 'Start following to customize your Feed',
      'noNewsYet': 'No news yet',
      'readOnSource': 'Read on source',
      'relatedAnime': 'Related Anime',
      'catAnnouncement': 'Announcement',
      'catSeason': 'Season',
      'catMovie': 'Movie',
      'catCollab': 'Collab',
      'catEvent': 'Event',
      'uploadVideo': 'Upload a video',
      'maxVideoDuration': 'Max 60 seconds',
      'videoTooLong': 'Video is too long — max 60 seconds',
      'pickFromGallery': 'Pick from gallery',
      'recordVideo': 'Record a video',
      'captionHint': 'Write a caption…',
      'uploading': 'Uploading…',
      'videoPosted': 'Video posted!',
      'videoUploadFailed': "Couldn't upload your video. Try again.",
      'noVideosYet': 'No videos yet — upload the first!',
      'videosLoadError': "Couldn't load videos.",
      'deleteVideo': 'Delete video',
      'videoDeleted': 'Video deleted',
      'reportVideo': 'Report video',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'This Week',
      'today': 'Today',
      'epShort': 'Ep',
      'noEpisodesThisWeek': 'No episodes airing this week.',
      'weekScheduleError': 'Couldn\'t load this week\'s schedule.\nCheck your connection and try again.',
      'dayMon': 'Mon', 'dayTue': 'Tue', 'dayWed': 'Wed', 'dayThu': 'Thu',
      'dayFri': 'Fri', 'daySat': 'Sat', 'daySun': 'Sun',
      'seasonWinter': 'Winter', 'seasonSpring': 'Spring',
      'seasonSummer': 'Summer', 'seasonFall': 'Fall',
    },
    'ar': {
      'vote': 'تصويت',
      'communityVoteTitle': 'تصويت المجتمع اليوم',
      'castVote': 'صوّت الآن',
      'votesRemaining': 'الأصوات المتبقية',
      'resetsIn': 'يتجدد خلال',
      'cantBeUndone': 'لا يمكن التراجع عن هذا.',
      'voteForConfirm': 'التصويت لـ',
      'alreadyVotedToday': 'لقد صوّت لهذا الأنمي اليوم بالفعل',
      'noVotesLeftToday': 'لا أصوات متبقية اليوم',
      'yourVotesToday': 'أصواتك اليوم',
      'todaysLeaderboard': 'متصدرو اليوم',
      'viewPastDays': 'عرض الأيام السابقة',
      'pastVotesTitle': 'تصويتات سابقة',
      'upgradeForVotes': 'AniPlus: ٤ أصوات يوميًا',
      'voteCastSuccess': 'تم التصويت! 🎉',
      'noVotesYetToday': 'لا أصوات بعد اليوم — كن الأول!',
      'searchAnimeHint': 'ابحث عن أنيمي…',
      'recentSearches': 'عمليات البحث الأخيرة',
      'noAnimeFound': 'لا نتائج لـ',
      'tagline': 'عالمك. أنيميك.',
      'feed': 'الرئيسية',
      'discover': 'اكتشف',
      'create': 'إنشاء',
      'rooms': 'الغرف',
      'community': 'المجتمع',
      'profile': 'الملف',
      'aniVideos': 'فيديوهات',
      'challenges': 'التحديات',
      'seasonal': 'الموسمي',
      'achievements': 'الإنجازات',
      'wallet': 'المحفظة',
      'observatory': 'المرصد',
      'fmRadio': 'راديو FM',
      'cardCollection': 'مجموعة البطاقات',
      'settings': 'الإعدادات',
      'myList': 'قائمتي',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'retry': 'إعادة المحاولة',
      'notes': 'ملاحظات',
      'status': 'الحالة',
      'total': 'الإجمالي',
      'removeFromList': 'إزالة من القائمة',
      'emptyListTitle': 'لا يوجد شيء هنا بعد',
      'emptyListBody': 'أضف أنمي للبدء',
      'episodesWatched': 'الحلقات المُشاهدة',
      'yourScore': 'تقييمك',
      'lastUpdated': 'آخر تحديث',
      'listError': 'تعذر تحديث قائمتك. حاول مجددًا.',
      'continueAsGuest': 'المتابعة كضيف',
      'guestSignedIn': 'تم تسجيل الدخول كضيف',
      'guestError': 'تعذر تسجيل الدخول. حاول مجددًا.',
      'messages': 'الرسائل',
      'notifications': 'الإشعارات',
      'selectLanguage': 'اختر اللغة',
      'createAccount': 'إنشاء حساب',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'skip': 'تخطّي',
      'next': 'التالي',
      'continueLabel': 'متابعة',
      'finishSetup': 'إنهاء الإعداد',
      'email': 'البريد الإلكتروني',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'dateOfBirth': 'تاريخ الميلاد',
      'account': 'الحساب',
      'pickAnime': 'اختر أنيمي',
      'preferences': 'التفضيلات',
      'firstAnimeEver': 'أول أنيمي شاهدته؟',
      'whatYouEnjoy': 'ماذا تحب؟',
      'ageRestriction': 'قيود العمر ⚠️',
      'ageRestrictionBody': 'يتطلب AniSphere أن يكون عمر المستخدمين 14 عامًا أو أكثر.',
      'exit': 'خروج',
      'follow': 'متابعة',
      'following': 'يتابع',
      'followers': 'المتابعون',
      'followBack': 'متابعة بالمقابل',
      'message': 'رسالة',
      'editProfile': 'تعديل الملف',
      'like': 'إعجاب',
      'comment': 'تعليق',
      'share': 'مشاركة',
      'bookmark': 'حفظ',
      'translate': 'ترجمة',
      'translated': 'مترجم',
      'showOriginal': 'النص الأصلي',
      'spoiler': 'حرق — اضغط للكشف',
      'trendingThisSeason': 'الرائج هذا الموسم',
      'dailyTasks': 'المهام اليومية',
      'stories': 'القصص',
      'addStory': 'أضف قصة',
      'forYou': 'لك',
      'trending': 'الرائج',
      'news': 'الأخبار',
      'aniMatch': 'توافق',
      'chart': 'التصنيف',
      'search': 'بحث',
      'searchHint': 'ابحث عن أنيمي، مستخدمين، منشورات…',
      'animeSoulmate': 'اعثر على توأم روحك الأنمي 💫',
      'match': 'توافق',
      'worldwide': 'عالميًا',
      'country': 'الدولة',
      'addToList': 'أضف للقائمة',
      'rate': 'قيّم',
      'watching': 'أشاهد',
      'completed': 'أكملت',
      'planning': 'سأشاهد',
      'onHold': 'معلّق',
      'dropped': 'متروك',
      'episodes': 'حلقات',
      'hours': 'ساعات',
      'anime': 'أنيمي',
      'posts': 'منشورات',
      'reviews': 'مراجعات',
      'lists': 'قوائم',
      'fanArt': 'فن المعجبين',
      'stats': 'إحصائيات',
      'games': 'ألعاب',
      'trueFan': 'المعجب الحقيقي',
      'league': 'الدوري',
      'events': 'فعاليات',
      'play': 'العب',
      'startChallenge': '→ ابدأ التحدي',
      'playAgain': 'العب مجددًا',
      'shareResult': 'شارك النتيجة',
      'whoIsThis': 'من هذه الشخصية؟',
      'correct': '+1 صحيح!',
      'worldRank': 'الترتيب العالمي',
      'countryRank': 'ترتيب الدولة',
      'earn': 'اكسب',
      'spend': 'أنفق',
      'recharge': 'اشحن',
      'aniPlus': 'AniPlus',
      'subscribeNow': 'اشترك الآن',
      'getVerified': 'احصل على التوثيق',
      'luckySpin': 'عجلة الحظ',
      'spin': 'أدر',
      'apply': 'تطبيق',
      'all': 'الكل',
      'follows': 'متابعات',
      'activity': 'نشاط',
      'streaks': 'سلاسل',
      'tasks': 'مهام',
      'logout': 'تسجيل الخروج',
      'about': 'حول',
      'terms': 'الشروط',
      'privacy': 'الخصوصية',
      'language': 'اللغة',
      'appearance': 'المظهر',
      'notificationSound': 'صوت الإشعار',
      'send': 'إرسال',
      'typing': 'يكتب…',
      'newPost': 'منشور جديد',
      'uploadAniVideo': 'رفع فيديو',
      'goLive': 'بث مباشر',
      'sealed': 'مغلق',
      'openPack': 'افتح الحزمة',
      'plusExclusive': 'حصري AniPlus 💎',
      'memberSince': 'عضو منذ',
      'streak': 'سلسلة',
      'verified': 'موثّق',
      'online': 'متصل',
      'post': 'نشر',
      'posted': 'تم النشر!',
      'newPostHint': 'شارك أفكارك عن الأنمي…',
      'addImage': 'أضف صورة',
      'tagAnime': 'وسم أنمي',
      'markAsSpoiler': 'وضع علامة حرق',
      'noPostsYet': 'لا منشورات بعد. تابع مستخدمين لرؤية منشوراتهم!',
      'comments': 'التعليقات',
      'noCommentsYet': 'لا تعليقات بعد — كن الأول!',
      'addCommentHint': 'أضف تعليقًا…',
      'deletePost': 'حذف المنشور',
      'reportPost': 'الإبلاغ عن المنشور',
      'postDeleted': 'تم حذف المنشور',
      'postReported': 'تم استلام البلاغ. شكرًا!',
      'postFailed': 'تعذر نشر منشورك. حاول مجددًا.',
      'maxImagesNote': 'يمكنك إضافة 3 صور كحد أقصى.',
      'imageTooLarge': 'تعذر تجهيز إحدى الصور للرفع. جرّب صورة أخرى.',
      'actionFailed': 'حدث خطأ ما. حاول مجددًا.',
      'noInternet': 'لا يوجد اتصال بالإنترنت.',
      'loadFeedError': 'تعذر تحميل الصفحة الرئيسية.',
      'whyReport': 'لماذا تبلغ عن هذا المنشور؟',
      'whyReportUser': 'لماذا تبلغ عن هذا المستخدم؟',
      'whyReportMessage': 'لماذا تبلغ عن هذه الرسالة؟',
      // ── Direct Messages ──
      'checkConnection': 'تحقق من اتصالك وحاول مجددًا.',
      'animeFanFallback': 'محب أنمي',
      'sayHi': 'قل مرحبًا 👋',
      'blockList': 'قائمة الحظر',
      'unblock': 'إلغاء الحظر',
      'block': 'حظر',
      'dmListError': 'الرسائل غير متاحة حاليًا.',
      'noMessagesYet': 'لا رسائل بعد',
      'noMessagesYetCaption': 'المحادثات التي تبدأها ستظهر هنا.',
      'blockListError': 'قائمة الحظر غير متاحة',
      'noBlockedConversations': 'لا محادثات محظورة',
      'noBlockedConversationsCaption': 'الأشخاص الذين تحظرهم من محادثة سيظهرون هنا.',
      'unblocking': 'جارٍ إلغاء الحظر…',
      'stillSending': 'ما زال قيد الإرسال — سيُرسل عند عودة الاتصال.',
      'sendMessageFailed': 'تعذر إرسال الرسالة.',
      'sendPhotoFailed': 'تعذر إرسال الصورة.',
      'conversationBlocked': 'تم حظر المحادثة',
      'conversationUnblocked': 'تم إلغاء حظر المحادثة',
      'reactionsBlocked': 'التفاعلات غير متاحة أثناء حظر هذه المحادثة.',
      'reportMessage': 'الإبلاغ عن الرسالة',
      'reportUser': 'الإبلاغ عن المستخدم',
      'conversationUnavailable': 'هذه المحادثة غير متاحة.',
      'messageHint': 'رسالة…',
      'conversationIsBlocked': 'هذه المحادثة محظورة',
      'conversationBlockedCaption': 'لا يمكن إرسال الرسائل أو استقبالها الآن.',
      'whoCanDM': 'من يمكنه المراسلة',
      'everyone': 'الجميع',
      'friends': 'الأصدقاء',
      'whyReportVideo': 'لماذا تبلغ عن هذا الفيديو؟',
      'reportSpam': 'إزعاج',
      'reportSpoiler': 'حرق بدون تحذير',
      'reportAbuse': 'تحرش أو إساءة',
      'reportOther': 'أخرى',
      'people': 'أشخاص',
      'suggestedForYou': 'مقترحون لك',
      'noSuggestions': 'لا مزيد من الاقتراحات',
      'noFollowersYet': 'لا متابعين بعد',
      'notFollowingAnyone': 'لا يتابع أحدًا بعد',
      'userNotFound': 'المستخدم غير موجود',
      'searchUsers': 'ابحث عن مستخدمين…',
      'likes': 'الإعجابات',
      'popularThisWeek': 'الرائج هذا الأسبوع',
      'emptyFeedFollow': 'تابع مستخدمين لترى منشوراتهم في صفحتك!',
      'startFollowingHint': 'ابدأ المتابعة لتخصيص صفحتك الرئيسية',
      'noNewsYet': 'لا أخبار بعد',
      'readOnSource': 'اقرأ من المصدر',
      'relatedAnime': 'أنميات ذات صلة',
      'catAnnouncement': 'إعلان',
      'catSeason': 'موسم',
      'catMovie': 'فيلم',
      'catCollab': 'تعاون',
      'catEvent': 'فعالية',
      'uploadVideo': 'ارفع فيديو',
      'maxVideoDuration': '٦٠ ثانية كحد أقصى',
      'videoTooLong': 'الفيديو طويل جدًا — الحد الأقصى ٦٠ ثانية',
      'pickFromGallery': 'اختر من المعرض',
      'recordVideo': 'سجّل فيديو',
      'captionHint': 'اكتب وصفًا…',
      'uploading': 'جارٍ الرفع…',
      'videoPosted': 'تم نشر الفيديو!',
      'videoUploadFailed': 'تعذّر رفع الفيديو. حاول مجددًا.',
      'noVideosYet': 'لا فيديوهات بعد — كن أول من يرفع!',
      'videosLoadError': 'تعذّر تحميل الفيديوهات.',
      'deleteVideo': 'حذف الفيديو',
      'videoDeleted': 'تم حذف الفيديو',
      'reportVideo': 'الإبلاغ عن الفيديو',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'هذا الأسبوع',
      'today': 'اليوم',
      'epShort': 'ح',
      'noEpisodesThisWeek': 'لا توجد حلقات تُعرض هذا الأسبوع.',
      'weekScheduleError': 'تعذّر تحميل جدول هذا الأسبوع.\nتحقّق من اتصالك وحاول مرة أخرى.',
      'dayMon': 'الاثنين', 'dayTue': 'الثلاثاء', 'dayWed': 'الأربعاء', 'dayThu': 'الخميس',
      'dayFri': 'الجمعة', 'daySat': 'السبت', 'daySun': 'الأحد',
      'seasonWinter': 'الشتاء', 'seasonSpring': 'الربيع',
      'seasonSummer': 'الصيف', 'seasonFall': 'الخريف',
    },
    'ja': {
      'vote': '投票',
      'communityVoteTitle': '今日のコミュニティ投票',
      'castVote': '投票する',
      'votesRemaining': '残り投票数',
      'resetsIn': 'リセットまで',
      'cantBeUndone': 'これは取り消せません。',
      'voteForConfirm': '投票:',
      'alreadyVotedToday': 'このアニメには今日すでに投票済みです',
      'noVotesLeftToday': '今日の投票は使い切りました',
      'yourVotesToday': '今日のあなたの投票',
      'todaysLeaderboard': '今日のランキング',
      'viewPastDays': '過去の結果を見る',
      'pastVotesTitle': '過去のコミュニティ投票',
      'upgradeForVotes': 'AniPlusで1日4票',
      'voteCastSuccess': '投票しました！🎉',
      'noVotesYetToday': 'まだ投票がありません — 一番乗りしよう！',
      'searchAnimeHint': 'アニメを検索…', 'recentSearches': '最近の検索', 'noAnimeFound': '見つかりませんでした:',
      'tagline': 'あなたの世界。あなたのアニメ。',
      'feed': 'フィード', 'discover': '発見', 'create': '作成', 'rooms': 'ルーム',
      'community': 'コミュニティ', 'profile': 'プロフィール', 'aniVideos': 'アニ動画',
      'challenges': 'チャレンジ', 'seasonal': '今期アニメ', 'achievements': '実績',
      'wallet': 'ウォレット', 'observatory': '天文台', 'fmRadio': 'FMラジオ',
      'cardCollection': 'カードコレクション', 'settings': '設定', 'myList': 'マイリスト',
      'save': '保存', 'cancel': 'キャンセル', 'retry': '再試行', 'notes': 'メモ',
      'status': 'ステータス', 'total': '合計', 'removeFromList': 'リストから削除',
      'emptyListTitle': 'まだ何もありません', 'emptyListBody': 'アニメを追加して始めよう',
      'episodesWatched': '視聴済み話数', 'yourScore': 'あなたの評価', 'lastUpdated': '最終更新',
      'listError': 'リストを更新できませんでした。もう一度お試しください。',
      'continueAsGuest': 'ゲストとして続行', 'guestSignedIn': 'ゲストとしてログインしました',
      'guestError': 'ログインできませんでした。もう一度お試しください。',
      'messages': 'メッセージ', 'notifications': '通知', 'selectLanguage': '言語を選択',
      'createAccount': 'アカウント作成', 'signIn': 'ログイン', 'signUp': '登録',
      'skip': 'スキップ', 'next': '次へ', 'continueLabel': '続ける', 'finishSetup': 'セットアップ完了',
      'email': 'メールアドレス', 'username': 'ユーザー名', 'password': 'パスワード',
      'dateOfBirth': '生年月日', 'account': 'アカウント', 'pickAnime': 'アニメを選ぶ',
      'preferences': '好み', 'firstAnimeEver': '初めて見たアニメは？', 'whatYouEnjoy': '何が好き？',
      'ageRestriction': '年齢制限 ⚠️', 'ageRestrictionBody': 'AniSphereのご利用は14歳以上が対象です。',
      'exit': '終了', 'follow': 'フォロー', 'following': 'フォロー中', 'followers': 'フォロワー',
      'followBack': 'フォローバック', 'message': 'メッセージ', 'editProfile': 'プロフィール編集',
      'like': 'いいね', 'comment': 'コメント', 'share': '共有', 'bookmark': '保存',
      'translate': '翻訳', 'translated': '翻訳済み', 'showOriginal': '原文を表示',
      'spoiler': 'ネタバレ — タップで表示', 'trendingThisSeason': '今期のトレンド',
      'dailyTasks': 'デイリータスク', 'stories': 'ストーリー', 'addStory': 'ストーリー追加',
      'forYou': 'おすすめ', 'trending': 'トレンド', 'news': 'ニュース', 'aniMatch': 'AniMatch',
      'chart': 'ランキング', 'search': '検索', 'searchHint': 'アニメ・ユーザー・投稿を検索…',
      'animeSoulmate': 'アニメの相性相手を探そう 💫', 'match': 'マッチ', 'worldwide': '世界', 'country': '国',
      'addToList': 'リストに追加', 'rate': '評価', 'watching': '視聴中', 'completed': '視聴済み',
      'planning': '視聴予定', 'onHold': '保留', 'dropped': '中断', 'episodes': '話数',
      'hours': '時間', 'anime': 'アニメ', 'posts': '投稿', 'reviews': 'レビュー', 'lists': 'リスト',
      'fanArt': 'ファンアート', 'stats': '統計', 'games': 'ゲーム', 'trueFan': '真のファン',
      'league': 'リーグ', 'events': 'イベント', 'play': 'プレイ', 'startChallenge': 'チャレンジ開始 →',
      'playAgain': 'もう一度', 'shareResult': '結果を共有', 'whoIsThis': 'このキャラは誰？',
      'correct': '+1 正解！', 'worldRank': '世界ランク', 'countryRank': '国内ランク',
      'earn': '稼ぐ', 'spend': '使う', 'recharge': 'チャージ', 'aniPlus': 'AniPlus',
      'subscribeNow': '今すぐ登録', 'getVerified': '認証を取得', 'luckySpin': 'ラッキースピン',
      'spin': 'スピン', 'apply': '適用', 'all': 'すべて', 'follows': 'フォロー', 'activity': 'アクティビティ',
      'streaks': '連続記録', 'tasks': 'タスク', 'logout': 'ログアウト', 'about': '概要', 'terms': '規約',
      'privacy': 'プライバシー', 'language': '言語', 'appearance': '外観', 'notificationSound': '通知音',
      'send': '送信', 'typing': '入力中…', 'newPost': '新規投稿', 'uploadAniVideo': 'アニ動画を投稿',
      'goLive': 'ライブ配信', 'sealed': '封印中', 'openPack': 'パックを開く', 'plusExclusive': 'AniPlus限定 💎',
      'memberSince': '登録日', 'streak': '連続記録', 'verified': '認証済み', 'online': 'オンライン',
      'post': '投稿', 'posted': '投稿しました！', 'newPostHint': 'アニメについてシェアしよう…',
      'addImage': '画像を追加', 'tagAnime': 'アニメをタグ付け', 'markAsSpoiler': 'ネタバレとしてマーク',
      'noPostsYet': 'まだ投稿がありません。ユーザーをフォローして投稿を見よう！',
      'comments': 'コメント', 'noCommentsYet': 'まだコメントがありません — 最初のコメントを！',
      'addCommentHint': 'コメントを追加…', 'deletePost': '投稿を削除', 'reportPost': '投稿を報告',
      'postDeleted': '投稿を削除しました', 'postReported': '報告を受け付けました。ありがとうございます！',
      'postFailed': '投稿できませんでした。もう一度お試しください。',
      'maxImagesNote': '画像は最大3枚まで追加できます。',
      'imageTooLarge': '画像をアップロード用に準備できませんでした。別の画像をお試しください。',
      'actionFailed': 'エラーが発生しました。もう一度お試しください。',
      'noInternet': 'インターネット接続がありません。', 'loadFeedError': 'フィードを読み込めませんでした。',
      'whyReport': 'この投稿を報告する理由は？', 'reportSpam': 'スパム', 'reportSpoiler': '未表示のネタバレ',
      'whyReportUser': 'このユーザーを報告する理由は？', 'whyReportMessage': 'このメッセージを報告する理由は？',
      // ── Direct Messages ──
      'checkConnection': '接続を確認して、もう一度お試しください。', 'animeFanFallback': 'アニメファン',
      'sayHi': 'あいさつしてみよう 👋', 'blockList': 'ブロックリスト',
      'unblock': 'ブロック解除', 'block': 'ブロック',
      'dmListError': '現在メッセージを表示できません。', 'noMessagesYet': 'メッセージはまだありません',
      'noMessagesYetCaption': '始めた会話がここに表示されます。', 'blockListError': 'ブロックリストを表示できません',
      'noBlockedConversations': 'ブロック中の会話はありません', 'noBlockedConversationsCaption': 'チャットからブロックした相手がここに表示されます。',
      'unblocking': 'ブロック解除中…', 'stillSending': '送信中です。オンラインに戻ると送信されます。',
      'sendMessageFailed': 'メッセージを送信できませんでした。', 'sendPhotoFailed': '写真を送信できませんでした。',
      'conversationBlocked': '会話をブロックしました', 'conversationUnblocked': '会話のブロックを解除しました',
      'reactionsBlocked': 'この会話がブロックされている間はリアクションできません。', 'reportMessage': 'メッセージを報告',
      'reportUser': 'ユーザーを報告', 'conversationUnavailable': 'この会話は利用できません。',
      'messageHint': 'メッセージ…', 'conversationIsBlocked': 'この会話はブロックされています',
      'conversationBlockedCaption': '現在メッセージの送受信はできません。', 'whoCanDM': 'DMできる人',
      'everyone': '全員', 'friends': '友だち',
      'whyReportVideo': 'この動画を報告する理由は？',
      'reportAbuse': '嫌がらせ・悪質行為', 'reportOther': 'その他',
      'people': 'ユーザー', 'suggestedForYou': 'おすすめユーザー', 'noSuggestions': 'これ以上おすすめはありません',
      'noFollowersYet': 'まだフォロワーがいません', 'notFollowingAnyone': 'まだ誰もフォローしていません',
      'userNotFound': 'ユーザーが見つかりません', 'searchUsers': 'ユーザーを検索…', 'likes': 'いいね',
      'popularThisWeek': '今週の人気', 'emptyFeedFollow': 'ユーザーをフォローするとフィードに投稿が表示されます！',
      'startFollowingHint': 'フォローしてフィードをカスタマイズしよう', 'noNewsYet': 'まだニュースがありません',
      'readOnSource': 'ソースで読む', 'relatedAnime': '関連アニメ', 'catAnnouncement': '発表',
      'catSeason': '新シーズン', 'catMovie': '映画', 'catCollab': 'コラボ', 'catEvent': 'イベント',
      'uploadVideo': '動画をアップロード', 'maxVideoDuration': '最大60秒',
      'videoTooLong': '動画が長すぎます — 最大60秒',
      'pickFromGallery': 'ギャラリーから選択', 'recordVideo': '動画を撮影',
      'captionHint': 'キャプションを書く…', 'uploading': 'アップロード中…',
      'videoPosted': '動画を投稿しました！',
      'videoUploadFailed': '動画をアップロードできませんでした。もう一度お試しください。',
      'noVideosYet': 'まだ動画がありません — 最初の投稿者になろう！',
      'videosLoadError': '動画を読み込めませんでした。',
      'deleteVideo': '動画を削除', 'videoDeleted': '動画を削除しました', 'reportVideo': '動画を報告',
      // ── This Week (seasonal schedule) ──
      'thisWeek': '今週', 'today': '今日', 'epShort': 'EP',
      'noEpisodesThisWeek': '今週放送されるエピソードはありません。',
      'weekScheduleError': '今週の放送スケジュールを読み込めませんでした。\n接続を確認して、もう一度お試しください。',
      'dayMon': '月', 'dayTue': '火', 'dayWed': '水', 'dayThu': '木',
      'dayFri': '金', 'daySat': '土', 'daySun': '日',
      'seasonWinter': '冬', 'seasonSpring': '春', 'seasonSummer': '夏', 'seasonFall': '秋',
    },
    'ko': {
      'vote': '투표',
      'communityVoteTitle': '오늘의 커뮤니티 투표',
      'castVote': '투표하기',
      'votesRemaining': '남은 투표',
      'resetsIn': '초기화까지',
      'cantBeUndone': '되돌릴 수 없어요.',
      'voteForConfirm': '투표:',
      'alreadyVotedToday': '오늘 이미 이 애니에 투표했어요',
      'noVotesLeftToday': '오늘 투표를 모두 사용했어요',
      'yourVotesToday': '오늘 내 투표',
      'todaysLeaderboard': '오늘의 순위',
      'viewPastDays': '지난 결과 보기',
      'pastVotesTitle': '지난 커뮤니티 투표',
      'upgradeForVotes': 'AniPlus: 하루 4표',
      'voteCastSuccess': '투표 완료! 🎉',
      'noVotesYetToday': '아직 투표가 없어요 — 첫 번째가 되어보세요!',
      'searchAnimeHint': '애니 검색…', 'recentSearches': '최근 검색', 'noAnimeFound': '검색 결과가 없어요:',
      'tagline': '당신의 세계. 당신의 애니.',
      'feed': '피드', 'discover': '탐색', 'create': '만들기', 'rooms': '룸',
      'community': '커뮤니티', 'profile': '프로필', 'aniVideos': '아니 비디오',
      'challenges': '챌린지', 'seasonal': '시즌 애니', 'achievements': '업적',
      'wallet': '지갑', 'observatory': '천문대', 'fmRadio': 'FM 라디오',
      'cardCollection': '카드 컬렉션', 'settings': '설정', 'myList': '내 목록',
      'save': '저장', 'cancel': '취소', 'retry': '다시 시도', 'notes': '메모',
      'status': '상태', 'total': '전체', 'removeFromList': '목록에서 제거',
      'emptyListTitle': '아직 아무것도 없어요', 'emptyListBody': '애니를 추가해 시작하세요',
      'episodesWatched': '시청한 에피소드', 'yourScore': '내 평점', 'lastUpdated': '마지막 업데이트',
      'listError': '목록을 업데이트하지 못했어요. 다시 시도하세요.',
      'continueAsGuest': '게스트로 계속', 'guestSignedIn': '게스트로 로그인했어요',
      'guestError': '로그인하지 못했어요. 다시 시도하세요.',
      'messages': '메시지', 'notifications': '알림', 'selectLanguage': '언어 선택',
      'createAccount': '계정 만들기', 'signIn': '로그인', 'signUp': '회원가입',
      'skip': '건너뛰기', 'next': '다음', 'continueLabel': '계속', 'finishSetup': '설정 완료',
      'email': '이메일', 'username': '사용자 이름', 'password': '비밀번호',
      'dateOfBirth': '생년월일', 'account': '계정', 'pickAnime': '애니 선택',
      'preferences': '환경설정', 'firstAnimeEver': '처음 본 애니는?', 'whatYouEnjoy': '무엇을 즐기나요?',
      'ageRestriction': '연령 제한 ⚠️', 'ageRestrictionBody': 'AniSphere는 만 14세 이상만 이용할 수 있습니다.',
      'exit': '종료', 'follow': '팔로우', 'following': '팔로잉', 'followers': '팔로워',
      'followBack': '맞팔로우', 'message': '메시지', 'editProfile': '프로필 편집',
      'like': '좋아요', 'comment': '댓글', 'share': '공유', 'bookmark': '저장',
      'translate': '번역', 'translated': '번역됨', 'showOriginal': '원문 보기',
      'spoiler': '스포일러 — 탭하여 보기', 'trendingThisSeason': '이번 시즌 인기',
      'dailyTasks': '일일 과제', 'stories': '스토리', 'addStory': '스토리 추가',
      'forYou': '추천', 'trending': '인기', 'news': '뉴스', 'aniMatch': 'AniMatch',
      'chart': '차트', 'search': '검색', 'searchHint': '애니, 사용자, 게시물 검색…',
      'animeSoulmate': '애니 소울메이트 찾기 💫', 'match': '매치', 'worldwide': '전 세계', 'country': '국가',
      'addToList': '목록에 추가', 'rate': '평가', 'watching': '시청 중', 'completed': '완료',
      'planning': '시청 예정', 'onHold': '보류', 'dropped': '중단', 'episodes': '에피소드',
      'hours': '시간', 'anime': '애니', 'posts': '게시물', 'reviews': '리뷰', 'lists': '목록',
      'fanArt': '팬아트', 'stats': '통계', 'games': '게임', 'trueFan': '진정한 팬',
      'league': '리그', 'events': '이벤트', 'play': '플레이', 'startChallenge': '챌린지 시작 →',
      'playAgain': '다시 하기', 'shareResult': '결과 공유', 'whoIsThis': '이 캐릭터는 누구일까요?',
      'correct': '+1 정답!', 'worldRank': '세계 순위', 'countryRank': '국가 순위',
      'earn': '획득', 'spend': '사용', 'recharge': '충전', 'aniPlus': 'AniPlus',
      'subscribeNow': '지금 구독', 'getVerified': '인증 받기', 'luckySpin': '행운의 룰렛',
      'spin': '돌리기', 'apply': '적용', 'all': '전체', 'follows': '팔로우', 'activity': '활동',
      'streaks': '연속 기록', 'tasks': '과제', 'logout': '로그아웃', 'about': '정보', 'terms': '약관',
      'privacy': '개인정보', 'language': '언어', 'appearance': '화면', 'notificationSound': '알림음',
      'send': '보내기', 'typing': '입력 중…', 'newPost': '새 게시물', 'uploadAniVideo': '아니 비디오 업로드',
      'goLive': '라이브 방송', 'sealed': '봉인됨', 'openPack': '팩 열기', 'plusExclusive': 'AniPlus 전용 💎',
      'memberSince': '가입일', 'streak': '연속 기록', 'verified': '인증됨', 'online': '온라인',
      'post': '게시', 'posted': '게시했어요!', 'newPostHint': '애니에 대한 생각을 공유하세요…',
      'addImage': '이미지 추가', 'tagAnime': '애니 태그', 'markAsSpoiler': '스포일러로 표시',
      'noPostsYet': '아직 게시물이 없어요. 사용자를 팔로우해 게시물을 확인하세요!',
      'comments': '댓글', 'noCommentsYet': '아직 댓글이 없어요 — 첫 댓글을 남겨보세요!',
      'addCommentHint': '댓글 추가…', 'deletePost': '게시물 삭제', 'reportPost': '게시물 신고',
      'postDeleted': '게시물을 삭제했어요', 'postReported': '신고가 접수됐어요. 감사합니다!',
      'postFailed': '게시물을 올리지 못했어요. 다시 시도하세요.',
      'maxImagesNote': '이미지는 최대 3장까지 추가할 수 있어요.',
      'imageTooLarge': '이미지를 업로드용으로 준비하지 못했어요. 다른 이미지를 사용해 보세요.',
      'actionFailed': '문제가 발생했어요. 다시 시도하세요.',
      'noInternet': '인터넷 연결이 없어요.', 'loadFeedError': '피드를 불러오지 못했어요.',
      'whyReport': '이 게시물을 신고하는 이유는?', 'reportSpam': '스팸', 'reportSpoiler': '표시 없는 스포일러',
      'whyReportUser': '이 사용자를 신고하는 이유는?', 'whyReportMessage': '이 메시지를 신고하는 이유는?',
      // ── Direct Messages ──
      'checkConnection': '연결을 확인하고 다시 시도하세요.', 'animeFanFallback': '애니 팬',
      'sayHi': '인사해 보세요 👋', 'blockList': '차단 목록',
      'unblock': '차단 해제', 'block': '차단',
      'dmListError': '지금은 메시지를 불러올 수 없어요.', 'noMessagesYet': '아직 메시지가 없어요',
      'noMessagesYetCaption': '시작한 대화가 여기에 표시돼요.', 'blockListError': '차단 목록을 불러올 수 없어요',
      'noBlockedConversations': '차단한 대화가 없어요', 'noBlockedConversationsCaption': '채팅에서 차단한 사람이 여기에 표시돼요.',
      'unblocking': '차단 해제 중…', 'stillSending': '아직 전송 중이에요 — 다시 연결되면 전송돼요.',
      'sendMessageFailed': '메시지를 보내지 못했어요.', 'sendPhotoFailed': '사진을 보내지 못했어요.',
      'conversationBlocked': '대화를 차단했어요', 'conversationUnblocked': '대화 차단을 해제했어요',
      'reactionsBlocked': '이 대화가 차단된 동안에는 반응을 남길 수 없어요.', 'reportMessage': '메시지 신고',
      'reportUser': '사용자 신고', 'conversationUnavailable': '이 대화를 사용할 수 없어요.',
      'messageHint': '메시지…', 'conversationIsBlocked': '이 대화는 차단되었어요',
      'conversationBlockedCaption': '지금은 메시지를 주고받을 수 없어요.', 'whoCanDM': 'DM 보낼 수 있는 사람',
      'everyone': '모두', 'friends': '친구',
      'whyReportVideo': '이 동영상을 신고하는 이유는?',
      'reportAbuse': '괴롭힘 또는 학대', 'reportOther': '기타',
      'people': '사람', 'suggestedForYou': '추천 사용자', 'noSuggestions': '더 이상 추천이 없어요',
      'noFollowersYet': '아직 팔로워가 없어요', 'notFollowingAnyone': '아직 아무도 팔로우하지 않아요',
      'userNotFound': '사용자를 찾을 수 없어요', 'searchUsers': '사용자 검색…', 'likes': '좋아요',
      'popularThisWeek': '이번 주 인기', 'emptyFeedFollow': '사용자를 팔로우하면 피드에 게시물이 보여요!',
      'startFollowingHint': '팔로우를 시작해 피드를 맞춤 설정하세요', 'noNewsYet': '아직 뉴스가 없어요',
      'readOnSource': '원문 보기', 'relatedAnime': '관련 애니', 'catAnnouncement': '발표',
      'catSeason': '시즌', 'catMovie': '영화', 'catCollab': '콜라보', 'catEvent': '이벤트',
      'uploadVideo': '동영상 업로드', 'maxVideoDuration': '최대 60초',
      'videoTooLong': '동영상이 너무 깁니다 — 최대 60초',
      'pickFromGallery': '갤러리에서 선택', 'recordVideo': '동영상 촬영',
      'captionHint': '캡션 작성…', 'uploading': '업로드 중…',
      'videoPosted': '동영상이 게시되었습니다!',
      'videoUploadFailed': '동영상을 업로드하지 못했습니다. 다시 시도해 주세요.',
      'noVideosYet': '아직 동영상이 없어요 — 첫 번째로 올려보세요!',
      'videosLoadError': '동영상을 불러오지 못했습니다.',
      'deleteVideo': '동영상 삭제', 'videoDeleted': '동영상이 삭제되었습니다', 'reportVideo': '동영상 신고',
      // ── This Week (seasonal schedule) ──
      'thisWeek': '이번 주', 'today': '오늘', 'epShort': 'EP',
      'noEpisodesThisWeek': '이번 주에 방영되는 에피소드가 없습니다.',
      'weekScheduleError': '이번 주 방영 일정을 불러오지 못했습니다.\n연결을 확인한 후 다시 시도해 주세요.',
      'dayMon': '월', 'dayTue': '화', 'dayWed': '수', 'dayThu': '목',
      'dayFri': '금', 'daySat': '토', 'daySun': '일',
      'seasonWinter': '겨울', 'seasonSpring': '봄', 'seasonSummer': '여름', 'seasonFall': '가을',
    },
    'es': {
      'vote': 'Votar',
      'communityVoteTitle': 'Voto comunitario de hoy',
      'castVote': 'Emitir un voto',
      'votesRemaining': 'Votos restantes',
      'resetsIn': 'Se reinicia en',
      'cantBeUndone': 'Esto no se puede deshacer.',
      'voteForConfirm': '¿Votar por',
      'alreadyVotedToday': 'Ya votaste por este anime hoy',
      'noVotesLeftToday': 'No te quedan votos hoy',
      'yourVotesToday': 'Tus votos de hoy',
      'todaysLeaderboard': 'Clasificación de hoy',
      'viewPastDays': 'Ver días anteriores',
      'pastVotesTitle': 'Votos comunitarios pasados',
      'upgradeForVotes': 'AniPlus: 4 votos/día',
      'voteCastSuccess': '¡Voto emitido! 🎉',
      'noVotesYetToday': 'Aún no hay votos hoy — ¡sé el primero!',
      'searchAnimeHint': 'Buscar anime…', 'recentSearches': 'Búsquedas recientes', 'noAnimeFound': 'No se encontró anime para',
      'tagline': 'Tu mundo. Tu anime.',
      'feed': 'Inicio', 'discover': 'Descubrir', 'create': 'Crear', 'rooms': 'Salas',
      'community': 'Comunidad', 'profile': 'Perfil', 'aniVideos': 'Ani Videos',
      'challenges': 'Retos', 'seasonal': 'Temporada', 'achievements': 'Logros',
      'wallet': 'Cartera', 'observatory': 'Observatorio', 'fmRadio': 'Radio FM',
      'cardCollection': 'Colección de cartas', 'settings': 'Ajustes', 'myList': 'Mi lista',
      'save': 'Guardar', 'cancel': 'Cancelar', 'retry': 'Reintentar', 'notes': 'Notas',
      'status': 'Estado', 'total': 'Total', 'removeFromList': 'Quitar de la lista',
      'emptyListTitle': 'Nada por aquí todavía', 'emptyListBody': 'Añade anime para empezar',
      'episodesWatched': 'Episodios vistos', 'yourScore': 'Tu puntuación', 'lastUpdated': 'Última actualización',
      'listError': 'No se pudo actualizar tu lista. Inténtalo de nuevo.',
      'continueAsGuest': 'Continuar como invitado', 'guestSignedIn': 'Sesión iniciada como invitado',
      'guestError': 'No se pudo iniciar sesión. Inténtalo de nuevo.',
      'messages': 'Mensajes', 'notifications': 'Notificaciones', 'selectLanguage': 'Seleccionar idioma',
      'createAccount': 'Crear cuenta', 'signIn': 'Entrar', 'signUp': 'Registrarse',
      'skip': 'Omitir', 'next': 'Siguiente', 'continueLabel': 'Continuar', 'finishSetup': 'Finalizar',
      'email': 'Correo', 'username': 'Usuario', 'password': 'Contraseña',
      'dateOfBirth': 'Fecha de nacimiento', 'account': 'Cuenta', 'pickAnime': 'Elige anime',
      'preferences': 'Preferencias', 'firstAnimeEver': '¿Tu primer anime?', 'whatYouEnjoy': '¿Qué te gusta?',
      'ageRestriction': 'Restricción de edad ⚠️', 'ageRestrictionBody': 'AniSphere requiere que los usuarios tengan 14 años o más.',
      'exit': 'Salir', 'follow': 'Seguir', 'following': 'Siguiendo', 'followers': 'Seguidores',
      'followBack': 'Seguir también', 'message': 'Mensaje', 'editProfile': 'Editar perfil',
      'like': 'Me gusta', 'comment': 'Comentar', 'share': 'Compartir', 'bookmark': 'Guardar',
      'translate': 'Traducir', 'translated': 'Traducido', 'showOriginal': 'Ver original',
      'spoiler': 'Spoiler — toca para ver', 'trendingThisSeason': 'Tendencia esta temporada',
      'dailyTasks': 'Tareas diarias', 'stories': 'Historias', 'addStory': 'Añadir historia',
      'forYou': 'Para ti', 'trending': 'Tendencia', 'news': 'Noticias', 'aniMatch': 'AniMatch',
      'chart': 'Ranking', 'search': 'Buscar', 'searchHint': 'Busca anime, usuarios, publicaciones…',
      'animeSoulmate': 'Encuentra tu alma gemela del anime 💫', 'match': 'Match', 'worldwide': 'Mundial', 'country': 'País',
      'addToList': 'Añadir a la lista', 'rate': 'Calificar', 'watching': 'Viendo', 'completed': 'Completado',
      'planning': 'Planeado', 'onHold': 'En pausa', 'dropped': 'Abandonado', 'episodes': 'Episodios',
      'hours': 'Horas', 'anime': 'Anime', 'posts': 'Publicaciones', 'reviews': 'Reseñas', 'lists': 'Listas',
      'fanArt': 'Fan art', 'stats': 'Estadísticas', 'games': 'Juegos', 'trueFan': 'Fan de verdad',
      'league': 'Liga', 'events': 'Eventos', 'play': 'Jugar', 'startChallenge': 'Empezar reto →',
      'playAgain': 'Jugar de nuevo', 'shareResult': 'Compartir resultado', 'whoIsThis': '¿Quién es este personaje?',
      'correct': '¡+1 Correcto!', 'worldRank': 'Ranking mundial', 'countryRank': 'Ranking nacional',
      'earn': 'Ganar', 'spend': 'Gastar', 'recharge': 'Recargar', 'aniPlus': 'AniPlus',
      'subscribeNow': 'Suscribirse', 'getVerified': 'Verifícate', 'luckySpin': 'Giro de la suerte',
      'spin': 'Girar', 'apply': 'Aplicar', 'all': 'Todo', 'follows': 'Seguidos', 'activity': 'Actividad',
      'streaks': 'Rachas', 'tasks': 'Tareas', 'logout': 'Cerrar sesión', 'about': 'Acerca de', 'terms': 'Términos',
      'privacy': 'Privacidad', 'language': 'Idioma', 'appearance': 'Apariencia', 'notificationSound': 'Sonido de notificación',
      'send': 'Enviar', 'typing': 'escribiendo…', 'newPost': 'Nueva publicación', 'uploadAniVideo': 'Subir Ani Video',
      'goLive': 'En directo', 'sealed': 'Sellado', 'openPack': 'Abrir sobre', 'plusExclusive': 'Exclusivo de AniPlus 💎',
      'memberSince': 'Miembro desde', 'streak': 'Racha', 'verified': 'Verificado', 'online': 'en línea',
      'post': 'Publicar', 'posted': '¡Publicado!', 'newPostHint': 'Comparte tus ideas sobre anime…',
      'addImage': 'Añadir imagen', 'tagAnime': 'Etiquetar anime', 'markAsSpoiler': 'Marcar como spoiler',
      'noPostsYet': 'Aún no hay publicaciones. ¡Sigue a usuarios para ver sus posts!',
      'comments': 'Comentarios', 'noCommentsYet': 'Aún no hay comentarios — ¡sé el primero!',
      'addCommentHint': 'Añade un comentario…', 'deletePost': 'Eliminar publicación', 'reportPost': 'Denunciar publicación',
      'postDeleted': 'Publicación eliminada', 'postReported': 'Denuncia recibida. ¡Gracias!',
      'postFailed': 'No se pudo publicar. Inténtalo de nuevo.',
      'maxImagesNote': 'Puedes añadir hasta 3 imágenes.',
      'imageTooLarge': 'No se pudo preparar una imagen para subir. Prueba con otra imagen.',
      'actionFailed': 'Algo salió mal. Inténtalo de nuevo.',
      'noInternet': 'Sin conexión a internet.', 'loadFeedError': 'No se pudo cargar el inicio.',
      'whyReport': '¿Por qué denuncias esta publicación?', 'reportSpam': 'Spam', 'reportSpoiler': 'Spoiler sin marcar',
      'whyReportUser': '¿Por qué denuncias a este usuario?', 'whyReportMessage': '¿Por qué denuncias este mensaje?',
      // ── Direct Messages ──
      'checkConnection': 'Comprueba tu conexión e inténtalo de nuevo.', 'animeFanFallback': 'Fan del anime',
      'sayHi': 'Saluda 👋', 'blockList': 'Lista de bloqueados',
      'unblock': 'Desbloquear', 'block': 'Bloquear',
      'dmListError': 'Los mensajes no están disponibles ahora mismo.', 'noMessagesYet': 'Aún no hay mensajes',
      'noMessagesYetCaption': 'Las conversaciones que inicies aparecerán aquí.', 'blockListError': 'Lista de bloqueados no disponible',
      'noBlockedConversations': 'No hay conversaciones bloqueadas', 'noBlockedConversationsCaption': 'Las personas que bloquees desde un chat aparecerán aquí.',
      'unblocking': 'Desbloqueando…', 'stillSending': 'Enviando aún: se enviará cuando vuelvas a estar en línea.',
      'sendMessageFailed': 'No se pudo enviar el mensaje.', 'sendPhotoFailed': 'No se pudo enviar la foto.',
      'conversationBlocked': 'Conversación bloqueada', 'conversationUnblocked': 'Conversación desbloqueada',
      'reactionsBlocked': 'Las reacciones no están disponibles mientras esta conversación esté bloqueada.', 'reportMessage': 'Denunciar mensaje',
      'reportUser': 'Denunciar usuario', 'conversationUnavailable': 'Esta conversación no está disponible.',
      'messageHint': 'Mensaje…', 'conversationIsBlocked': 'Esta conversación está bloqueada',
      'conversationBlockedCaption': 'Ahora mismo no se pueden enviar ni recibir mensajes.', 'whoCanDM': 'Quién puede enviarte MD',
      'everyone': 'Todos', 'friends': 'Amigos',
      'whyReportVideo': '¿Por qué denuncias este video?',
      'reportAbuse': 'Acoso o abuso', 'reportOther': 'Otro',
      'people': 'Personas', 'suggestedForYou': 'Sugerencias para ti', 'noSuggestions': 'No hay más sugerencias',
      'noFollowersYet': 'Aún no hay seguidores', 'notFollowingAnyone': 'Aún no sigue a nadie',
      'userNotFound': 'Usuario no encontrado', 'searchUsers': 'Buscar usuarios…', 'likes': 'Me gusta',
      'popularThisWeek': 'Popular esta semana', 'emptyFeedFollow': '¡Sigue a usuarios para ver sus posts en tu Inicio!',
      'startFollowingHint': 'Empieza a seguir para personalizar tu Inicio', 'noNewsYet': 'Aún no hay noticias',
      'readOnSource': 'Leer en la fuente', 'relatedAnime': 'Anime relacionado', 'catAnnouncement': 'Anuncio',
      'catSeason': 'Temporada', 'catMovie': 'Película', 'catCollab': 'Colaboración', 'catEvent': 'Evento',
      'uploadVideo': 'Subir un video', 'maxVideoDuration': 'Máximo 60 segundos',
      'videoTooLong': 'El video es demasiado largo — máximo 60 segundos',
      'pickFromGallery': 'Elegir de la galería', 'recordVideo': 'Grabar un video',
      'captionHint': 'Escribe una descripción…', 'uploading': 'Subiendo…',
      'videoPosted': '¡Video publicado!',
      'videoUploadFailed': 'No se pudo subir el video. Inténtalo de nuevo.',
      'noVideosYet': 'Aún no hay videos — ¡sube el primero!',
      'videosLoadError': 'No se pudieron cargar los videos.',
      'deleteVideo': 'Eliminar video', 'videoDeleted': 'Video eliminado', 'reportVideo': 'Reportar video',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'Esta semana', 'today': 'Hoy', 'epShort': 'Ep',
      'noEpisodesThisWeek': 'No hay episodios en emisión esta semana.',
      'weekScheduleError': 'No se pudo cargar la programación de esta semana.\nComprueba tu conexión e inténtalo de nuevo.',
      'dayMon': 'Lun', 'dayTue': 'Mar', 'dayWed': 'Mié', 'dayThu': 'Jue',
      'dayFri': 'Vie', 'daySat': 'Sáb', 'daySun': 'Dom',
      'seasonWinter': 'Invierno', 'seasonSpring': 'Primavera',
      'seasonSummer': 'Verano', 'seasonFall': 'Otoño',
    },
    'fr': {
      'vote': 'Voter',
      'communityVoteTitle': 'Vote communautaire du jour',
      'castVote': 'Voter maintenant',
      'votesRemaining': 'Votes restants',
      'resetsIn': 'Réinitialisation dans',
      'cantBeUndone': 'Impossible à annuler.',
      'voteForConfirm': 'Voter pour',
      'alreadyVotedToday': 'Tu as déjà voté pour cet anime aujourd’hui',
      'noVotesLeftToday': 'Plus de votes aujourd’hui',
      'yourVotesToday': 'Tes votes du jour',
      'todaysLeaderboard': 'Classement du jour',
      'viewPastDays': 'Voir les jours passés',
      'pastVotesTitle': 'Votes communautaires passés',
      'upgradeForVotes': 'AniPlus : 4 votes/jour',
      'voteCastSuccess': 'Vote enregistré ! 🎉',
      'noVotesYetToday': 'Aucun vote aujourd’hui — sois le premier !',
      'searchAnimeHint': 'Rechercher un anime…', 'recentSearches': 'Recherches récentes', 'noAnimeFound': 'Aucun anime trouvé pour',
      'tagline': 'Ton monde. Ton anime.',
      'feed': 'Accueil', 'discover': 'Découvrir', 'create': 'Créer', 'rooms': 'Salons',
      'community': 'Communauté', 'profile': 'Profil', 'aniVideos': 'Ani Vidéos',
      'challenges': 'Défis', 'seasonal': 'Saison', 'achievements': 'Succès',
      'wallet': 'Portefeuille', 'observatory': 'Observatoire', 'fmRadio': 'Radio FM',
      'cardCollection': 'Collection de cartes', 'settings': 'Réglages', 'myList': 'Ma liste',
      'save': 'Enregistrer', 'cancel': 'Annuler', 'retry': 'Réessayer', 'notes': 'Notes',
      'status': 'Statut', 'total': 'Total', 'removeFromList': 'Retirer de la liste',
      'emptyListTitle': "Rien ici pour l'instant", 'emptyListBody': 'Ajoute un anime pour commencer',
      'episodesWatched': 'Épisodes vus', 'yourScore': 'Ta note', 'lastUpdated': 'Dernière mise à jour',
      'listError': 'Impossible de mettre à jour ta liste. Réessaie.',
      'continueAsGuest': 'Continuer en invité', 'guestSignedIn': "Connecté en tant qu'invité",
      'guestError': 'Connexion impossible. Réessaie.',
      'messages': 'Messages', 'notifications': 'Notifications', 'selectLanguage': 'Choisir la langue',
      'createAccount': 'Créer un compte', 'signIn': 'Connexion', 'signUp': "S'inscrire",
      'skip': 'Passer', 'next': 'Suivant', 'continueLabel': 'Continuer', 'finishSetup': 'Terminer',
      'email': 'E-mail', 'username': "Nom d'utilisateur", 'password': 'Mot de passe',
      'dateOfBirth': 'Date de naissance', 'account': 'Compte', 'pickAnime': 'Choisir un anime',
      'preferences': 'Préférences', 'firstAnimeEver': 'Ton premier anime ?', 'whatYouEnjoy': 'Qu’aimes-tu ?',
      'ageRestriction': 'Restriction d’âge ⚠️', 'ageRestrictionBody': 'AniSphere est réservé aux utilisateurs de 14 ans et plus.',
      'exit': 'Quitter', 'follow': 'Suivre', 'following': 'Abonnements', 'followers': 'Abonnés',
      'followBack': 'Suivre en retour', 'message': 'Message', 'editProfile': 'Modifier le profil',
      'like': "J'aime", 'comment': 'Commenter', 'share': 'Partager', 'bookmark': 'Enregistrer',
      'translate': 'Traduire', 'translated': 'Traduit', 'showOriginal': "Voir l'original",
      'spoiler': 'Spoiler — appuie pour révéler', 'trendingThisSeason': 'Tendance cette saison',
      'dailyTasks': 'Tâches quotidiennes', 'stories': 'Stories', 'addStory': 'Ajouter une story',
      'forYou': 'Pour toi', 'trending': 'Tendances', 'news': 'Actus', 'aniMatch': 'AniMatch',
      'chart': 'Classement', 'search': 'Rechercher', 'searchHint': 'Rechercher anime, utilisateurs, posts…',
      'animeSoulmate': 'Trouve ton âme sœur anime 💫', 'match': 'Match', 'worldwide': 'Mondial', 'country': 'Pays',
      'addToList': 'Ajouter à la liste', 'rate': 'Noter', 'watching': 'En cours', 'completed': 'Terminé',
      'planning': 'Prévu', 'onHold': 'En pause', 'dropped': 'Abandonné', 'episodes': 'Épisodes',
      'hours': 'Heures', 'anime': 'Anime', 'posts': 'Posts', 'reviews': 'Critiques', 'lists': 'Listes',
      'fanArt': 'Fan art', 'stats': 'Stats', 'games': 'Jeux', 'trueFan': 'Vrai fan',
      'league': 'Ligue', 'events': 'Événements', 'play': 'Jouer', 'startChallenge': 'Commencer le défi →',
      'playAgain': 'Rejouer', 'shareResult': 'Partager le résultat', 'whoIsThis': 'Qui est ce personnage ?',
      'correct': '+1 Correct !', 'worldRank': 'Rang mondial', 'countryRank': 'Rang national',
      'earn': 'Gagner', 'spend': 'Dépenser', 'recharge': 'Recharger', 'aniPlus': 'AniPlus',
      'subscribeNow': "S'abonner", 'getVerified': 'Être vérifié', 'luckySpin': 'Roue de la chance',
      'spin': 'Tourner', 'apply': 'Appliquer', 'all': 'Tout', 'follows': 'Abonnements', 'activity': 'Activité',
      'streaks': 'Séries', 'tasks': 'Tâches', 'logout': 'Déconnexion', 'about': 'À propos', 'terms': 'Conditions',
      'privacy': 'Confidentialité', 'language': 'Langue', 'appearance': 'Apparence', 'notificationSound': 'Son de notification',
      'send': 'Envoyer', 'typing': 'écrit…', 'newPost': 'Nouveau post', 'uploadAniVideo': 'Publier une Ani Vidéo',
      'goLive': 'Direct', 'sealed': 'Scellé', 'openPack': 'Ouvrir un pack', 'plusExclusive': 'Exclusif AniPlus 💎',
      'memberSince': 'Membre depuis', 'streak': 'Série', 'verified': 'Vérifié', 'online': 'en ligne',
      'post': 'Publier', 'posted': 'Publié !', 'newPostHint': 'Partage tes pensées anime…',
      'addImage': 'Ajouter une image', 'tagAnime': 'Taguer un anime', 'markAsSpoiler': 'Marquer comme spoiler',
      'noPostsYet': 'Pas encore de posts. Suis des utilisateurs pour voir leurs posts !',
      'comments': 'Commentaires', 'noCommentsYet': 'Pas encore de commentaires — sois le premier !',
      'addCommentHint': 'Ajouter un commentaire…', 'deletePost': 'Supprimer le post', 'reportPost': 'Signaler le post',
      'postDeleted': 'Post supprimé', 'postReported': 'Signalement reçu. Merci !',
      'postFailed': 'Impossible de publier. Réessaie.',
      'maxImagesNote': "Tu peux ajouter jusqu'à 3 images.",
      'imageTooLarge': "Impossible de préparer une image pour l'envoi. Essaie une autre image.",
      'actionFailed': "Une erreur s'est produite. Réessaie.",
      'noInternet': 'Pas de connexion internet.', 'loadFeedError': 'Impossible de charger le fil.',
      'whyReport': 'Pourquoi signales-tu ce post ?', 'reportSpam': 'Spam', 'reportSpoiler': 'Spoiler non signalé',
      'whyReportUser': 'Pourquoi signales-tu cet utilisateur ?', 'whyReportMessage': 'Pourquoi signales-tu ce message ?',
      // ── Direct Messages ──
      'checkConnection': 'Vérifie ta connexion et réessaie.', 'animeFanFallback': "Fan d'anime",
      'sayHi': 'Dis bonjour 👋', 'blockList': 'Liste de blocage',
      'unblock': 'Débloquer', 'block': 'Bloquer',
      'dmListError': 'Les messages sont indisponibles pour le moment.', 'noMessagesYet': 'Pas encore de messages',
      'noMessagesYetCaption': 'Les conversations que tu démarres apparaîtront ici.', 'blockListError': 'Liste de blocage indisponible',
      'noBlockedConversations': 'Aucune conversation bloquée', 'noBlockedConversationsCaption': 'Les personnes que tu bloques depuis une conversation apparaîtront ici.',
      'unblocking': 'Déblocage…', 'stillSending': 'Envoi en cours — le message partira dès que tu seras de nouveau en ligne.',
      'sendMessageFailed': "Impossible d'envoyer le message.", 'sendPhotoFailed': "Impossible d'envoyer la photo.",
      'conversationBlocked': 'Conversation bloquée', 'conversationUnblocked': 'Conversation débloquée',
      'reactionsBlocked': 'Les réactions sont indisponibles tant que cette conversation est bloquée.', 'reportMessage': 'Signaler le message',
      'reportUser': "Signaler l'utilisateur", 'conversationUnavailable': 'Cette conversation est indisponible.',
      'messageHint': 'Message…', 'conversationIsBlocked': 'Cette conversation est bloquée',
      'conversationBlockedCaption': "Impossible d'envoyer ou de recevoir des messages pour le moment.", 'whoCanDM': 'Qui peut envoyer un MP',
      'everyone': 'Tout le monde', 'friends': 'Amis',
      'whyReportVideo': 'Pourquoi signales-tu cette vidéo ?',
      'reportAbuse': 'Harcèlement ou abus', 'reportOther': 'Autre',
      'people': 'Utilisateurs', 'suggestedForYou': 'Suggestions pour toi', 'noSuggestions': 'Plus de suggestions',
      'noFollowersYet': "Pas encore d'abonnés", 'notFollowingAnyone': 'Ne suit encore personne',
      'userNotFound': 'Utilisateur introuvable', 'searchUsers': 'Rechercher des utilisateurs…', 'likes': "J'aime",
      'popularThisWeek': 'Populaire cette semaine', 'emptyFeedFollow': 'Suis des utilisateurs pour voir leurs posts dans ton fil !',
      'startFollowingHint': 'Commence à suivre pour personnaliser ton fil', 'noNewsYet': 'Pas encore de news',
      'readOnSource': 'Lire sur la source', 'relatedAnime': 'Anime liés', 'catAnnouncement': 'Annonce',
      'catSeason': 'Saison', 'catMovie': 'Film', 'catCollab': 'Collab', 'catEvent': 'Événement',
      'uploadVideo': 'Publier une vidéo', 'maxVideoDuration': '60 secondes max',
      'videoTooLong': 'Vidéo trop longue — 60 secondes max',
      'pickFromGallery': 'Choisir dans la galerie', 'recordVideo': 'Filmer une vidéo',
      'captionHint': 'Écris une légende…', 'uploading': 'Envoi en cours…',
      'videoPosted': 'Vidéo publiée !',
      'videoUploadFailed': "Impossible d'envoyer la vidéo. Réessaie.",
      'noVideosYet': 'Pas encore de vidéos — publie la première !',
      'videosLoadError': 'Impossible de charger les vidéos.',
      'deleteVideo': 'Supprimer la vidéo', 'videoDeleted': 'Vidéo supprimée', 'reportVideo': 'Signaler la vidéo',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'Cette semaine', 'today': 'Aujourd\'hui', 'epShort': 'Ép',
      'noEpisodesThisWeek': 'Aucun épisode diffusé cette semaine.',
      'weekScheduleError': 'Impossible de charger le programme de cette semaine.\nVérifiez votre connexion et réessayez.',
      'dayMon': 'Lun', 'dayTue': 'Mar', 'dayWed': 'Mer', 'dayThu': 'Jeu',
      'dayFri': 'Ven', 'daySat': 'Sam', 'daySun': 'Dim',
      'seasonWinter': 'Hiver', 'seasonSpring': 'Printemps',
      'seasonSummer': 'Été', 'seasonFall': 'Automne',
    },
    'tr': {
      'vote': 'Oy ver',
      'communityVoteTitle': 'Bugünün Topluluk Oylaması',
      'castVote': 'Oy kullan',
      'votesRemaining': 'Kalan oylar',
      'resetsIn': 'Sıfırlanmasına',
      'cantBeUndone': 'Bu geri alınamaz.',
      'voteForConfirm': 'Oy ver:',
      'alreadyVotedToday': 'Bu animeye bugün zaten oy verdin',
      'noVotesLeftToday': 'Bugün oy hakkın kalmadı',
      'yourVotesToday': 'Bugünkü oyların',
      'todaysLeaderboard': 'Bugünün sıralaması',
      'viewPastDays': 'Geçmiş günleri gör',
      'pastVotesTitle': 'Geçmiş topluluk oylamaları',
      'upgradeForVotes': 'AniPlus: günde 4 oy',
      'voteCastSuccess': 'Oy verildi! 🎉',
      'noVotesYetToday': 'Bugün henüz oy yok — ilk sen ol!',
      'searchAnimeHint': 'Anime ara…', 'recentSearches': 'Son aramalar', 'noAnimeFound': 'Şununla ilgili anime bulunamadı:',
      'tagline': 'Senin dünyan. Senin animen.',
      'feed': 'Akış', 'discover': 'Keşfet', 'create': 'Oluştur', 'rooms': 'Odalar',
      'community': 'Topluluk', 'profile': 'Profil', 'aniVideos': 'Ani Videolar',
      'challenges': 'Görevler', 'seasonal': 'Sezon', 'achievements': 'Başarımlar',
      'wallet': 'Cüzdan', 'observatory': 'Gözlemevi', 'fmRadio': 'FM Radyo',
      'cardCollection': 'Kart Koleksiyonu', 'settings': 'Ayarlar', 'myList': 'Listem',
      'save': 'Kaydet', 'cancel': 'İptal', 'retry': 'Tekrar dene', 'notes': 'Notlar',
      'status': 'Durum', 'total': 'Toplam', 'removeFromList': 'Listeden çıkar',
      'emptyListTitle': 'Henüz bir şey yok', 'emptyListBody': 'Başlamak için anime ekle',
      'episodesWatched': 'İzlenen bölümler', 'yourScore': 'Puanın', 'lastUpdated': 'Son güncelleme',
      'listError': 'Listen güncellenemedi. Tekrar dene.',
      'continueAsGuest': 'Misafir olarak devam et', 'guestSignedIn': 'Misafir olarak giriş yapıldı',
      'guestError': 'Giriş yapılamadı. Tekrar dene.',
      'messages': 'Mesajlar', 'notifications': 'Bildirimler', 'selectLanguage': 'Dil seç',
      'createAccount': 'Hesap Oluştur', 'signIn': 'Giriş', 'signUp': 'Kayıt Ol',
      'skip': 'Atla', 'next': 'İleri', 'continueLabel': 'Devam', 'finishSetup': 'Kurulumu bitir',
      'email': 'E-posta', 'username': 'Kullanıcı adı', 'password': 'Şifre',
      'dateOfBirth': 'Doğum tarihi', 'account': 'Hesap', 'pickAnime': 'Anime seç',
      'preferences': 'Tercihler', 'firstAnimeEver': 'İlk animen?', 'whatYouEnjoy': 'Neyi seversin?',
      'ageRestriction': 'Yaş Kısıtlaması ⚠️', 'ageRestrictionBody': 'AniSphere için 14 yaş ve üzeri olmanız gerekir.',
      'exit': 'Çıkış', 'follow': 'Takip Et', 'following': 'Takip ediliyor', 'followers': 'Takipçiler',
      'followBack': 'Geri takip et', 'message': 'Mesaj', 'editProfile': 'Profili düzenle',
      'like': 'Beğen', 'comment': 'Yorum', 'share': 'Paylaş', 'bookmark': 'Kaydet',
      'translate': 'Çevir', 'translated': 'Çevrildi', 'showOriginal': 'Orijinali göster',
      'spoiler': 'Spoiler — görmek için dokun', 'trendingThisSeason': 'Bu sezon gündemde',
      'dailyTasks': 'Günlük görevler', 'stories': 'Hikayeler', 'addStory': 'Hikaye ekle',
      'forYou': 'Sana Özel', 'trending': 'Gündem', 'news': 'Haberler', 'aniMatch': 'AniMatch',
      'chart': 'Sıralama', 'search': 'Ara', 'searchHint': 'Anime, kullanıcı, gönderi ara…',
      'animeSoulmate': 'Anime ruh eşini bul 💫', 'match': 'Eşleşme', 'worldwide': 'Dünya', 'country': 'Ülke',
      'addToList': 'Listeye ekle', 'rate': 'Puanla', 'watching': 'İzleniyor', 'completed': 'Tamamlandı',
      'planning': 'Planlanan', 'onHold': 'Beklemede', 'dropped': 'Bırakıldı', 'episodes': 'Bölümler',
      'hours': 'Saat', 'anime': 'Anime', 'posts': 'Gönderiler', 'reviews': 'İncelemeler', 'lists': 'Listeler',
      'fanArt': 'Fan Art', 'stats': 'İstatistik', 'games': 'Oyunlar', 'trueFan': 'Gerçek Hayran',
      'league': 'Lig', 'events': 'Etkinlikler', 'play': 'Oyna', 'startChallenge': 'Meydan okumayı başlat →',
      'playAgain': 'Tekrar oyna', 'shareResult': 'Sonucu paylaş', 'whoIsThis': 'Bu karakter kim?',
      'correct': '+1 Doğru!', 'worldRank': 'Dünya sırası', 'countryRank': 'Ülke sırası',
      'earn': 'Kazan', 'spend': 'Harca', 'recharge': 'Yükle', 'aniPlus': 'AniPlus',
      'subscribeNow': 'Şimdi abone ol', 'getVerified': 'Onaylan', 'luckySpin': 'Şans Çarkı',
      'spin': 'Çevir', 'apply': 'Uygula', 'all': 'Tümü', 'follows': 'Takipler', 'activity': 'Etkinlik',
      'streaks': 'Seriler', 'tasks': 'Görevler', 'logout': 'Çıkış yap', 'about': 'Hakkında', 'terms': 'Koşullar',
      'privacy': 'Gizlilik', 'language': 'Dil', 'appearance': 'Görünüm', 'notificationSound': 'Bildirim sesi',
      'send': 'Gönder', 'typing': 'yazıyor…', 'newPost': 'Yeni gönderi', 'uploadAniVideo': 'Ani Video yükle',
      'goLive': 'Canlı yayın', 'sealed': 'Mühürlü', 'openPack': 'Paket aç', 'plusExclusive': 'AniPlus’a özel 💎',
      'memberSince': 'Üyelik', 'streak': 'Seri', 'verified': 'Onaylı', 'online': 'çevrimiçi',
      'post': 'Paylaş', 'posted': 'Paylaşıldı!', 'newPostHint': 'Anime düşüncelerini paylaş…',
      'addImage': 'Görsel ekle', 'tagAnime': 'Anime etiketle', 'markAsSpoiler': 'Spoiler olarak işaretle',
      'noPostsYet': 'Henüz gönderi yok. Gönderilerini görmek için kullanıcıları takip et!',
      'comments': 'Yorumlar', 'noCommentsYet': 'Henüz yorum yok — ilk yorumu sen yap!',
      'addCommentHint': 'Yorum ekle…', 'deletePost': 'Gönderiyi sil', 'reportPost': 'Gönderiyi bildir',
      'postDeleted': 'Gönderi silindi', 'postReported': 'Bildirim alındı. Teşekkürler!',
      'postFailed': 'Gönderin paylaşılamadı. Tekrar dene.',
      'maxImagesNote': 'En fazla 3 görsel ekleyebilirsin.',
      'imageTooLarge': 'Bir görsel yükleme için hazırlanamadı. Başka bir görsel dene.',
      'actionFailed': 'Bir şeyler ters gitti. Tekrar dene.',
      'noInternet': 'İnternet bağlantısı yok.', 'loadFeedError': 'Akış yüklenemedi.',
      'whyReport': 'Bu gönderiyi neden bildiriyorsun?', 'reportSpam': 'Spam', 'reportSpoiler': 'İşaretlenmemiş spoiler',
      'whyReportUser': 'Bu kullanıcıyı neden bildiriyorsun?', 'whyReportMessage': 'Bu mesajı neden bildiriyorsun?',
      // ── Direct Messages ──
      'checkConnection': 'Bağlantını kontrol et ve tekrar dene.', 'animeFanFallback': 'Anime hayranı',
      'sayHi': 'Selam ver 👋', 'blockList': 'Engellenenler',
      'unblock': 'Engeli kaldır', 'block': 'Engelle',
      'dmListError': 'Mesajlar şu anda kullanılamıyor.', 'noMessagesYet': 'Henüz mesaj yok',
      'noMessagesYetCaption': 'Başlattığın sohbetler burada görünür.', 'blockListError': 'Engellenenler listesi kullanılamıyor',
      'noBlockedConversations': 'Engellenen sohbet yok', 'noBlockedConversationsCaption': 'Bir sohbetten engellediğin kişiler burada görünür.',
      'unblocking': 'Engel kaldırılıyor…', 'stillSending': 'Hâlâ gönderiliyor — tekrar çevrimiçi olduğunda gidecek.',
      'sendMessageFailed': 'Mesaj gönderilemedi.', 'sendPhotoFailed': 'Fotoğraf gönderilemedi.',
      'conversationBlocked': 'Sohbet engellendi', 'conversationUnblocked': 'Sohbetin engeli kaldırıldı',
      'reactionsBlocked': 'Bu sohbet engelliyken tepki verilemez.', 'reportMessage': 'Mesajı bildir',
      'reportUser': 'Kullanıcıyı bildir', 'conversationUnavailable': 'Bu sohbet kullanılamıyor.',
      'messageHint': 'Mesaj…', 'conversationIsBlocked': 'Bu sohbet engellendi',
      'conversationBlockedCaption': 'Şu anda mesaj gönderilemez veya alınamaz.', 'whoCanDM': 'Kimler DM atabilir',
      'everyone': 'Herkes', 'friends': 'Arkadaşlar',
      'whyReportVideo': 'Bu videoyu neden bildiriyorsun?',
      'reportAbuse': 'Taciz veya kötüye kullanım', 'reportOther': 'Diğer',
      'people': 'Kişiler', 'suggestedForYou': 'Senin için önerilenler', 'noSuggestions': 'Başka öneri yok',
      'noFollowersYet': 'Henüz takipçi yok', 'notFollowingAnyone': 'Henüz kimseyi takip etmiyor',
      'userNotFound': 'Kullanıcı bulunamadı', 'searchUsers': 'Kullanıcı ara…', 'likes': 'Beğeniler',
      'popularThisWeek': 'Bu hafta popüler', 'emptyFeedFollow': 'Akışında gönderileri görmek için kullanıcıları takip et!',
      'startFollowingHint': 'Akışını kişiselleştirmek için takibe başla', 'noNewsYet': 'Henüz haber yok',
      'readOnSource': 'Kaynakta oku', 'relatedAnime': 'İlgili animeler', 'catAnnouncement': 'Duyuru',
      'catSeason': 'Sezon', 'catMovie': 'Film', 'catCollab': 'İş birliği', 'catEvent': 'Etkinlik',
      'uploadVideo': 'Video yükle', 'maxVideoDuration': 'En fazla 60 saniye',
      'videoTooLong': 'Video çok uzun — en fazla 60 saniye',
      'pickFromGallery': 'Galeriden seç', 'recordVideo': 'Video çek',
      'captionHint': 'Bir açıklama yaz…', 'uploading': 'Yükleniyor…',
      'videoPosted': 'Video paylaşıldı!',
      'videoUploadFailed': 'Video yüklenemedi. Tekrar dene.',
      'noVideosYet': 'Henüz video yok — ilkini sen yükle!',
      'videosLoadError': 'Videolar yüklenemedi.',
      'deleteVideo': 'Videoyu sil', 'videoDeleted': 'Video silindi', 'reportVideo': 'Videoyu bildir',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'Bu hafta', 'today': 'Bugün', 'epShort': 'Böl',
      'noEpisodesThisWeek': 'Bu hafta yayınlanan bölüm yok.',
      'weekScheduleError': 'Bu haftanın yayın takvimi yüklenemedi.\nBağlantını kontrol edip tekrar dene.',
      'dayMon': 'Pzt', 'dayTue': 'Sal', 'dayWed': 'Çar', 'dayThu': 'Per',
      'dayFri': 'Cum', 'daySat': 'Cmt', 'daySun': 'Paz',
      'seasonWinter': 'Kış', 'seasonSpring': 'İlkbahar',
      'seasonSummer': 'Yaz', 'seasonFall': 'Sonbahar',
    },
    'id': {
      'vote': 'Vote',
      'communityVoteTitle': 'Vote Komunitas Hari Ini',
      'castVote': 'Kirim vote',
      'votesRemaining': 'Sisa vote',
      'resetsIn': 'Reset dalam',
      'cantBeUndone': 'Ini tidak bisa dibatalkan.',
      'voteForConfirm': 'Vote untuk',
      'alreadyVotedToday': 'Kamu sudah vote anime ini hari ini',
      'noVotesLeftToday': 'Vote hari ini sudah habis',
      'yourVotesToday': 'Vote-mu hari ini',
      'todaysLeaderboard': 'Peringkat hari ini',
      'viewPastDays': 'Lihat hari sebelumnya',
      'pastVotesTitle': 'Vote komunitas sebelumnya',
      'upgradeForVotes': 'AniPlus: 4 vote/hari',
      'voteCastSuccess': 'Vote terkirim! 🎉',
      'noVotesYetToday': 'Belum ada vote hari ini — jadilah yang pertama!',
      'searchAnimeHint': 'Cari anime…', 'recentSearches': 'Pencarian terakhir', 'noAnimeFound': 'Anime tidak ditemukan untuk',
      'tagline': 'Duniamu. Animemu.',
      'feed': 'Beranda', 'discover': 'Jelajah', 'create': 'Buat', 'rooms': 'Ruang',
      'community': 'Komunitas', 'profile': 'Profil', 'aniVideos': 'Ani Video',
      'challenges': 'Tantangan', 'seasonal': 'Musiman', 'achievements': 'Pencapaian',
      'wallet': 'Dompet', 'observatory': 'Observatorium', 'fmRadio': 'Radio FM',
      'cardCollection': 'Koleksi Kartu', 'settings': 'Pengaturan', 'myList': 'Daftar Saya',
      'save': 'Simpan', 'cancel': 'Batal', 'retry': 'Coba lagi', 'notes': 'Catatan',
      'status': 'Status', 'total': 'Total', 'removeFromList': 'Hapus dari daftar',
      'emptyListTitle': 'Belum ada apa-apa', 'emptyListBody': 'Tambahkan anime untuk memulai',
      'episodesWatched': 'Episode ditonton', 'yourScore': 'Nilaimu', 'lastUpdated': 'Terakhir diperbarui',
      'listError': 'Gagal memperbarui daftarmu. Coba lagi.',
      'continueAsGuest': 'Lanjut sebagai tamu', 'guestSignedIn': 'Masuk sebagai tamu',
      'guestError': 'Gagal masuk. Coba lagi.',
      'messages': 'Pesan', 'notifications': 'Notifikasi', 'selectLanguage': 'Pilih bahasa',
      'createAccount': 'Buat Akun', 'signIn': 'Masuk', 'signUp': 'Daftar',
      'skip': 'Lewati', 'next': 'Lanjut', 'continueLabel': 'Lanjutkan', 'finishSetup': 'Selesai',
      'email': 'Email', 'username': 'Nama pengguna', 'password': 'Kata sandi',
      'dateOfBirth': 'Tanggal lahir', 'account': 'Akun', 'pickAnime': 'Pilih anime',
      'preferences': 'Preferensi', 'firstAnimeEver': 'Anime pertamamu?', 'whatYouEnjoy': 'Apa yang kamu suka?',
      'ageRestriction': 'Batasan Usia ⚠️', 'ageRestrictionBody': 'AniSphere mengharuskan pengguna berusia 14 tahun ke atas.',
      'exit': 'Keluar', 'follow': 'Ikuti', 'following': 'Mengikuti', 'followers': 'Pengikut',
      'followBack': 'Ikuti balik', 'message': 'Pesan', 'editProfile': 'Edit profil',
      'like': 'Suka', 'comment': 'Komentar', 'share': 'Bagikan', 'bookmark': 'Simpan',
      'translate': 'Terjemahkan', 'translated': 'Diterjemahkan', 'showOriginal': 'Tampilkan asli',
      'spoiler': 'Spoiler — ketuk untuk lihat', 'trendingThisSeason': 'Tren musim ini',
      'dailyTasks': 'Tugas harian', 'stories': 'Cerita', 'addStory': 'Tambah cerita',
      'forYou': 'Untukmu', 'trending': 'Tren', 'news': 'Berita', 'aniMatch': 'AniMatch',
      'chart': 'Peringkat', 'search': 'Cari', 'searchHint': 'Cari anime, pengguna, postingan…',
      'animeSoulmate': 'Temukan belahan jiwa anime-mu 💫', 'match': 'Cocok', 'worldwide': 'Dunia', 'country': 'Negara',
      'addToList': 'Tambah ke daftar', 'rate': 'Nilai', 'watching': 'Ditonton', 'completed': 'Selesai',
      'planning': 'Rencana', 'onHold': 'Ditunda', 'dropped': 'Berhenti', 'episodes': 'Episode',
      'hours': 'Jam', 'anime': 'Anime', 'posts': 'Postingan', 'reviews': 'Ulasan', 'lists': 'Daftar',
      'fanArt': 'Fan Art', 'stats': 'Statistik', 'games': 'Game', 'trueFan': 'Fan Sejati',
      'league': 'Liga', 'events': 'Acara', 'play': 'Main', 'startChallenge': 'Mulai tantangan →',
      'playAgain': 'Main lagi', 'shareResult': 'Bagikan hasil', 'whoIsThis': 'Siapa karakter ini?',
      'correct': '+1 Benar!', 'worldRank': 'Peringkat dunia', 'countryRank': 'Peringkat negara',
      'earn': 'Dapatkan', 'spend': 'Belanja', 'recharge': 'Isi ulang', 'aniPlus': 'AniPlus',
      'subscribeNow': 'Langganan sekarang', 'getVerified': 'Verifikasi', 'luckySpin': 'Putaran Keberuntungan',
      'spin': 'Putar', 'apply': 'Terapkan', 'all': 'Semua', 'follows': 'Ikuti', 'activity': 'Aktivitas',
      'streaks': 'Rentetan', 'tasks': 'Tugas', 'logout': 'Keluar', 'about': 'Tentang', 'terms': 'Ketentuan',
      'privacy': 'Privasi', 'language': 'Bahasa', 'appearance': 'Tampilan', 'notificationSound': 'Suara notifikasi',
      'send': 'Kirim', 'typing': 'mengetik…', 'newPost': 'Postingan baru', 'uploadAniVideo': 'Unggah Ani Video',
      'goLive': 'Siaran langsung', 'sealed': 'Tersegel', 'openPack': 'Buka paket', 'plusExclusive': 'Eksklusif AniPlus 💎',
      'memberSince': 'Anggota sejak', 'streak': 'Rentetan', 'verified': 'Terverifikasi', 'online': 'online',
      'post': 'Posting', 'posted': 'Terkirim!', 'newPostHint': 'Bagikan pendapatmu tentang anime…',
      'addImage': 'Tambah gambar', 'tagAnime': 'Tandai anime', 'markAsSpoiler': 'Tandai sebagai spoiler',
      'noPostsYet': 'Belum ada postingan. Ikuti pengguna untuk melihat postingan mereka!',
      'comments': 'Komentar', 'noCommentsYet': 'Belum ada komentar — jadilah yang pertama!',
      'addCommentHint': 'Tambahkan komentar…', 'deletePost': 'Hapus postingan', 'reportPost': 'Laporkan postingan',
      'postDeleted': 'Postingan dihapus', 'postReported': 'Laporan diterima. Terima kasih!',
      'postFailed': 'Gagal memposting. Coba lagi.',
      'maxImagesNote': 'Kamu bisa menambahkan hingga 3 gambar.',
      'imageTooLarge': 'Gagal menyiapkan gambar untuk diunggah. Coba gambar lain.',
      'actionFailed': 'Terjadi kesalahan. Coba lagi.',
      'noInternet': 'Tidak ada koneksi internet.', 'loadFeedError': 'Gagal memuat beranda.',
      'whyReport': 'Mengapa kamu melaporkan postingan ini?', 'reportSpam': 'Spam', 'reportSpoiler': 'Spoiler tanpa tanda',
      'whyReportUser': 'Mengapa kamu melaporkan pengguna ini?', 'whyReportMessage': 'Mengapa kamu melaporkan pesan ini?',
      // ── Direct Messages ──
      'checkConnection': 'Periksa koneksimu dan coba lagi.', 'animeFanFallback': 'Penggemar anime',
      'sayHi': 'Sapa dulu 👋', 'blockList': 'Daftar Blokir',
      'unblock': 'Buka blokir', 'block': 'Blokir',
      'dmListError': 'Pesan tidak tersedia saat ini.', 'noMessagesYet': 'Belum ada pesan',
      'noMessagesYetCaption': 'Percakapan yang kamu mulai akan muncul di sini.', 'blockListError': 'Daftar blokir tidak tersedia',
      'noBlockedConversations': 'Tidak ada percakapan yang diblokir', 'noBlockedConversationsCaption': 'Orang yang kamu blokir dari chat akan muncul di sini.',
      'unblocking': 'Membuka blokir…', 'stillSending': 'Masih mengirim — akan terkirim begitu kamu online lagi.',
      'sendMessageFailed': 'Gagal mengirim pesan.', 'sendPhotoFailed': 'Gagal mengirim foto.',
      'conversationBlocked': 'Percakapan diblokir', 'conversationUnblocked': 'Blokir percakapan dibuka',
      'reactionsBlocked': 'Reaksi tidak tersedia selama percakapan ini diblokir.', 'reportMessage': 'Laporkan pesan',
      'reportUser': 'Laporkan pengguna', 'conversationUnavailable': 'Percakapan ini tidak tersedia.',
      'messageHint': 'Pesan…', 'conversationIsBlocked': 'Percakapan ini diblokir',
      'conversationBlockedCaption': 'Pesan tidak bisa dikirim atau diterima sekarang.', 'whoCanDM': 'Siapa yang bisa DM',
      'everyone': 'Semua orang', 'friends': 'Teman',
      'whyReportVideo': 'Mengapa kamu melaporkan video ini?',
      'reportAbuse': 'Pelecehan atau penyalahgunaan', 'reportOther': 'Lainnya',
      'people': 'Orang', 'suggestedForYou': 'Disarankan untukmu', 'noSuggestions': 'Tidak ada saran lagi',
      'noFollowersYet': 'Belum ada pengikut', 'notFollowingAnyone': 'Belum mengikuti siapa pun',
      'userNotFound': 'Pengguna tidak ditemukan', 'searchUsers': 'Cari pengguna…', 'likes': 'Suka',
      'popularThisWeek': 'Populer minggu ini', 'emptyFeedFollow': 'Ikuti pengguna untuk melihat postingan di Berandamu!',
      'startFollowingHint': 'Mulai mengikuti untuk menyesuaikan Berandamu', 'noNewsYet': 'Belum ada berita',
      'readOnSource': 'Baca di sumber', 'relatedAnime': 'Anime terkait', 'catAnnouncement': 'Pengumuman',
      'catSeason': 'Musim', 'catMovie': 'Film', 'catCollab': 'Kolaborasi', 'catEvent': 'Acara',
      'uploadVideo': 'Unggah video', 'maxVideoDuration': 'Maksimal 60 detik',
      'videoTooLong': 'Video terlalu panjang — maksimal 60 detik',
      'pickFromGallery': 'Pilih dari galeri', 'recordVideo': 'Rekam video',
      'captionHint': 'Tulis keterangan…', 'uploading': 'Mengunggah…',
      'videoPosted': 'Video diposting!',
      'videoUploadFailed': 'Gagal mengunggah video. Coba lagi.',
      'noVideosYet': 'Belum ada video — jadilah yang pertama mengunggah!',
      'videosLoadError': 'Gagal memuat video.',
      'deleteVideo': 'Hapus video', 'videoDeleted': 'Video dihapus', 'reportVideo': 'Laporkan video',
      // ── This Week (seasonal schedule) ──
      'thisWeek': 'Minggu ini', 'today': 'Hari ini', 'epShort': 'Eps',
      'noEpisodesThisWeek': 'Tidak ada episode yang tayang minggu ini.',
      'weekScheduleError': 'Tidak dapat memuat jadwal minggu ini.\nPeriksa koneksimu dan coba lagi.',
      'dayMon': 'Sen', 'dayTue': 'Sel', 'dayWed': 'Rab', 'dayThu': 'Kam',
      'dayFri': 'Jum', 'daySat': 'Sab', 'daySun': 'Min',
      'seasonWinter': 'Musim Dingin', 'seasonSpring': 'Musim Semi',
      'seasonSummer': 'Musim Panas', 'seasonFall': 'Musim Gugur',
    },
  };

  /// Look up a key for [lang], falling back to English, then the key itself.
  static String t(String lang, String key) {
    return values[lang]?[key] ?? values['en']?[key] ?? key;
  }
}

class LangMeta {
  final String code;
  final String name;
  final String flag;
  final bool isRTL;
  const LangMeta(this.code, this.name, this.flag, {this.isRTL = false});
}
